### PR TITLE
feat(jtk): fix fields, field-options, archive, and get --extended compliance gaps

### LINKED ISSUE #282: jtk issues: fix fields, field-options, archive, and get --extended compliance gaps
Parent: #230

### `jtk issues fields <key>` (default)
**Current:** emits `FIELD_ID | NAME | TYPE | REQUIRED` — only editable fields, not current values.
**Expected:**
```
FIELD_ID | NAME | TYPE | VALUE
summary | Summary | string | Audit and remediate accessibility issues...
status | Status | status | In Code Review
assignee | Assignee | user | Aaron Wong
customfield_10035 | Story Points | number | 5
customfield_10050 | Team | option | Platform
...
```

### `jtk issues fields <key> --custom-fields`
**Current:** flag present but filtering is broken — standard fields still included.
**Expected:** only `customfield_*` rows emitted.

### `jtk issues field-options <key> <fieldId>`
**Current:** errors out ("field not in edit metadata").
**Expected:** uses the field-options API (not edit metadata), emits:
```
ID | VALUE | DISABLED
20001 | Platform | no
20002 | Integration | no
20003 | Frontend | no
```

### `jtk issues archive <key>`
**Current:** command missing — not in `jtk issues` help.
**Expected:**
```
Archived MON-4820
```

### `jtk issues get <key> --extended`
**Current:** missing Fix Versions, Watchers, Resolution rows; missing non-null custom fields block; missing Transitions block; description still truncated.
**Expected additions on top of default output:**
```
Fix Versions: -
Watchers: 2 (watching: yes)
Resolution: -
customfield_10044: On Track   (Meta Status)
customfield_10050: Platform   (Team)

Transitions:
  11 | Backlog
  21 | Ready for Development
  ...
```
Extended also implies `--fulltext` — description must not be truncated.

See #230 for full spec.

### PR DESCRIPTION
**Pull request by rianjs**
## Summary
- **`issues fields <key>`**: Shows all fields with current values (FIELD_ID|NAME|TYPE|VALUE) instead of only editable fields
- **`issues fields <key> --custom-fields`**: Now correctly filters to `customfield_*` rows only
- **`issues field-options <issue-key> <field>`**: Three-tier resolution (edit meta → default context → global) so read-only fields work
- **`issues archive <key>`**: New command using bulk `PUT /rest/api/3/issue/archive` API with partial failure handling
- **`issues get <key> --extended`**: Adds Fix Versions, Watchers, Resolution, non-null custom fields block, and Transitions table. Extended always implies fulltext.

## Test plan
- [ ] `make build` passes
- [ ] `make test` passes (all existing + new tests)
- [ ] `make lint` clean (no new issues)
- [ ] `jtk issues fields MON-4810` shows field values
- [ ] `jtk issues fields MON-4810 --custom-fields` shows only custom fields
- [ ] `jtk issues field-options MON-4810 customfield_10050` works for read-only fields
- [ ] `jtk issues archive MON-XXXX` archives an issue
- [ ] `jtk issues get MON-4810 --extended` shows all new sections

Closes #282

### CODE REVIEW

**Comment by rianjs** [comment]
**Blocker**
- `tools/jtk/internal/cmd/issues/get.go:85` + `tools/jtk/internal/present/issue.go:457`: `--extended --fields Watchers` still does not work. The projected branch returns before building `DetailContext`, and `PresentDetailProjection` hardcodes `Watchers`, `Custom_Fields`, and `Transitions` to `"-"`. This also means `--extended --fields Description` does not force fulltext. Build `DetailContext` before the projected branch when `opts.IsExtended()`, pass it into projection rendering, and force `noTruncate = true`.
- `tools/jtk/api/fields.go:271`: the context-options pagination loop can become infinite. `GetFieldContextOptions(ctx, fieldID, ctxID)` has no `startAt` argument, so when `page.IsLast == false` and `len(page.Values) > 0`, the loop refetches the same page forever. Add paginated API support or remove the loop.

**Major**
- `tools/jtk/api/fields.go:258`: `ResolveFieldOptions` falls back on any editmeta error. An invalid/unauthorized issue key can silently return default/global options, which violates the issue-key contract. Only fall back when editmeta was reachable but the field/options were absent.
- `tools/jtk/api/issues.go:207`: `ArchiveIssues` treats an unparseable response as full success with `NumberUpdated: len(keys)`. That can report archived issues that were not archived. Return the parse error instead.

**Minor**
- `tools/jtk/internal/cmd/issues/archive.go:48`: `archive` does not honor global `--id`; automation users should get raw archived keys instead of success messages.

**Comment by rianjs** [comment]
**Blocker**
- `tools/jtk/internal/cmd/issues/get.go:91` + `tools/jtk/internal/present/issue.go:457`: `--extended --fields Watchers`, `Transitions`, and `Custom_Fields` still render `"-"`. `runGet` builds `dctx`, but the projected path does not pass it anywhere, and `PresentDetailProjection` hardcodes those values. This misses the product goal for extended projection.

**Major**
- `tools/jtk/internal/cmd/issues/archive.go:53`: `archive --id` returns before checking `failedKeys`, so partial or total failures exit successfully after emitting only successes/nothing. Emit IDs, then still return `ErrAlreadyReported` when failures exist.
- `tools/jtk/api/fields.go:270`: context options now fetch only the first page. That avoids the previous infinite loop, but silently drops options when Jira paginates. Add real pagination support to `GetFieldContextOptions` or a paged wrapper.
- `tools/jtk/internal/cmd/issues/get.go:87` + `tools/jtk/internal/present/issue.go:376`: transition fetch errors are swallowed and the Transitions block is omitted entirely. Since #282 explicitly requires a Transitions block, either fail the command or render a clear empty/degraded block.
- PR metadata lists no `*_test.go` changes. The planned parity, fallback, archive partial-failure, and extended-output tests are not present, leaving these compliance paths unguarded.

**Minor**
- None.

**Nit**
- None.

**Comment by rianjs** [comment]
**Blocker**
- None.

**Major**
- `tools/jtk/api/fields.go:270`: `ResolveFieldOptions` still returns only the first context-options page. `FieldContextOptionsResponse` is paginated, so fields with more than one page of options will silently omit valid values.
- Test coverage is still incomplete for two core #282 paths: `issues fields <key>` / `--custom-fields`, and `issues field-options <issue-key> <field>` including editmeta → context → global fallback. The added tests cover archive and full extended get, but not these compliance changes.

**Minor**
- `tools/jtk/internal/cmd/issues/get.go:87` + `tools/jtk/internal/present/issue.go:374`: transition API failure is rendered as `(none available)`, which conflates “no transitions” with “could not fetch transitions.” Prefer failing or rendering an explicit unavailable state.
- `tools/jtk/api/fields.go:261`: detecting “field absent from editmeta” via error-string matching is brittle. A typed/sentinel error from `GetFieldOptionsFromEditMeta` would make this safer.

**Nit**
- None.

**Comment by rianjs** [comment]
**Blocker**
- None.

**Major**
- None.

**Minor**
- `tools/jtk/internal/cmd/issues/get_test.go`: add a regression test for `--extended --fields Watchers,Transitions,Custom_Fields,Description`. The full extended path is covered, but the projected extended path is the one that previously missed `DetailContext` and fulltext behavior.

**Nit**
- None.

**Comment by rianjs** [comment]
## TDD Assessment

Overall the test suite is solid for the happy paths and covers the main integration scenarios. There are a few meaningful gaps worth addressing before merge.

---

### Critical paths — covered

- `ResolveFieldOptions` tier-2 fallback (edit meta → context options) is exercised by `TestRunFieldOptions_FallbackToContext`.
- `ArchiveIssues` success, partial failure, and `--id` output are all tested in `archive_test.go`.
- Extended output sections (Resolution, FixVersions, Watchers, Transitions) are exercised by `TestRunGet_Extended_ShowsNewSections`.
- `--extended --fields` projection is covered by `TestRunGet_ExtendedFields_ProjectionUsesDetailContext`.
- `ExtractIssueFieldValues` for known struct fields and custom fields is indirectly exercised by `TestRunIssueFields_ShowsFieldValues` and `TestRunIssueFields_CustomOnly`.

---

### Gaps

**1. `ResolveFieldOptions` unit tests are entirely missing from the `api` package.**

`ResolveFieldOptions` (and `getAllContextOptions`) have no direct unit tests. The only coverage is through the command-layer `TestRunFieldOptions_FallbackToContext`, which exercises tier-2 but not the other scenarios:

- Tier-1 hit (edit meta returns non-empty) — not tested at the `api` level.
- Tier-2 context fetch succeeds but returns zero options — the function silently falls through to tier-3. This edge case is untested and the "silent skip on empty context options" behaviour is the most surprising part of the logic.
- Tier-3 global fallback — not tested at any level.
- All tiers exhausted (returns "no options found" error) — not tested.
- Non-`ErrFieldNotInEditMeta` error from `GetFieldOptionsFromEditMeta` triggers an early return — not tested.

**2. `ExtractIssueFieldValues` and `FormatCustomFieldValue` have no unit tests.**

These are new exported functions in `issues.go`. There are no tests in `api/issues_test.go` for them. Missing cases:

- `ExtractIssueFieldValues` with a nil `CustomFields` entry (the `if raw == nil { continue }` guard).
- `FormatCustomFieldValue` with `map[string]any` having none of `value`, `name`, or `displayName` keys (hits the `fmt.Sprintf("%v", val)` fallback).
- `FormatCustomFieldValue` with nested `[]any` containing non-string, non-map items (the `default` case in the inner switch is a no-op; items are silently dropped).
- `FormatCustomFieldValue` with a `bool` value (new `case bool:` branch).

**3. `ArchiveIssues` API-level is untested.**

`api/issues_test.go` has no test for `ArchiveIssues`. It's covered only through the command layer. Edge cases that only make sense at the API layer:

- Empty keys slice returns `ErrIssueKeyRequired`.
- Non-200 HTTP response surfaces a wrapped error.
- Malformed JSON response returns a parse error.

**4. `getAllContextOptions` pagination is not tested.**

The loop continues when `!page.IsLast && len(page.Values) > 0`. There is no test that exercises multi-page context option fetching (i.e., `isLast: false` on page 1, `isLast: true` on page 2).

**5. Transitions fetch failure in `--extended` mode.**

`runGet` with `--extended` calls `/transitions` and `/watchers`. There is no test for the scenario where the transitions call returns an error — the command should either degrade gracefully or propagate the error. Same for the watchers call. Neither failure path is covered.

---

### Minor flags

- `TestRunFieldOptions_FallbackToContext` asserts `testutil.Contains(t, stdout.String(), "DISABLED")` but both returned options have `"disabled": false`. This assertion will pass only if the presenter emits a column header named `DISABLED` — which may be the intent, but it reads as if it's asserting an option is flagged disabled when none are. Worth a comment clarifying the intent.
- `ErrFieldNotInEditMeta` is declared as `var ... = fmt.Errorf(...)`. This should be `errors.New(...)` — `fmt.Errorf` without `%w` is identical to `errors.New` here, but the inconsistency is a lint/style flag and may confuse future readers who expect `errors.Is` wrapping semantics to work through a `fmt.Errorf` chain.

---

### Recommended additions (priority order)

1. Unit tests for `ResolveFieldOptions` in `api/fields_test.go` covering all three tiers, empty-opts tier-2 fallthrough, and the non-`ErrFieldNotInEditMeta` early return.
2. Unit tests for `ExtractIssueFieldValues` and `FormatCustomFieldValue` in `api/issues_test.go`.
3. Unit tests for `ArchiveIssues` in `api/issues_test.go` (empty keys, HTTP error, parse error).
4. A pagination test for `getAllContextOptions`.
5. Error-path tests for `runGet --extended` when transitions or watchers fetches fail.

File: tools/jtk/api/fields.go [hunk 1]
```diff
@@ -250,3 +251,63 @@ func (c *Client) GetFieldOptionsFromEditMeta(ctx context.Context, issueKey, fiel
 
 	return options, nil
 }
+
```
Comment (monit-reviewer) [inline tools/jtk/api/fields.go:255]: 🟡 **Medium** (harness-engineering:harness-architecture-reviewer): ResolveFieldOptions falls through to context/global tiers when editErr is nil but opts is empty. A field that genuinely has zero configured options in edit meta will trigger two unnecessary extra API calls and may return options from a broader context that are invalid for the issue's project. The condition should distinguish 'field absent from edit meta' (fall through) from 'field present with no options' (return empty).

*Reply to this thread when addressed.*

File: tools/jtk/internal/cmd/issues/archive.go [hunk 2]
```diff
@@ -0,0 +1,72 @@
...
+	client, err := opts.APIClient()
+	if err != nil {
+		return err
+	}
+
+	result, err := client.ArchiveIssues(ctx, keys)
+	if err != nil {
+		return err
+	}
+
```
Comment (monit-reviewer) [inline tools/jtk/internal/cmd/issues/archive.go:41]: 🟡 **Medium** (harness-engineering:harness-enforcement-reviewer): Two compounding bugs in failure detection: (1) failedKeys is keyed on ae.IssueIdsOrKeys values from the API, which may be numeric IDs (e.g. '10042') rather than user-supplied keys (e.g. 'TEST-1'), so the lookup on line 48 never matches and all keys appear successful even on partial failure; (2) result.NumberUpdated is ignored entirely, so a no-op archive (all issues already archived, NumberUpdated=0, empty Errors) reports all input keys as successfully archived.

*Reply to this thread when addressed.*

File: tools/jtk/api/issues.go [hunk 3]
```diff
@@ -179,6 +181,263 @@ func ParseEditMeta(fieldsData map[string]any) []EditFieldMeta {
...
+
+// IssueFieldEntry represents a single field's current value on an issue,
+// used by `issues fields <key>` to display FIELD_ID|NAME|TYPE|VALUE.
+type IssueFieldEntry struct {
+	ID    string
+	Name  string
+	Type  string
+	Value string
+}
+
```
Comment (monit-reviewer) [inline tools/jtk/api/issues.go:251]: 🟡 **Medium** (harness-engineering:harness-knowledge-reviewer): Description truncation uses byte-slice indexing (`t[:80]`) rather than rune-aware slicing. For descriptions containing multi-byte UTF-8 characters whose boundary falls inside the first 80 bytes, this produces garbled output or panics with an invalid slice index. Use `[]rune(t)[:80]` or a utf8-aware trim.

*Reply to this thread when addressed.*

File: tools/jtk/api/fields.go [hunk 4]
```diff
@@ -250,3 +251,63 @@ func (c *Client) GetFieldOptionsFromEditMeta(ctx context.Context, issueKey, fiel
...
+	globalOpts, globalErr := c.GetFieldOptions(ctx, fieldID)
+	if globalErr == nil && len(globalOpts) > 0 {
+		return globalOpts, nil
+	}
+
+	return nil, fmt.Errorf("no options found for field %s on %s", fieldID, issueKey)
+}
+
+// ErrFieldNotInEditMeta is returned when a field is not present in the issue's
```
Comment (monit-reviewer) [inline tools/jtk/api/fields.go:289]: 🔵 **Low** (security:security-code-auditor): getAllContextOptions interpolates fieldID and contextID directly via fmt.Sprintf without url.PathEscape. Every other URL construction in this package escapes dynamic segments (e.g. GetIssueEditMeta, GetWatchers). While current Jira field and context IDs are safe, this is inconsistent and fragile.

*Reply to this thread when addressed.*

File: tools/jtk/internal/cmd/issues/get.go [hunk 5]
```diff
@@ -85,12 +82,34 @@ func runGet(ctx context.Context, opts *root.Options, issueKey string, noTruncate
 	}
 
 	presenter := jtkpresent.IssuePresenter{}
+
+	if opts.IsExtended() {
+		noTruncate = true
+		transitions, transErr := client.GetTransitions(ctx, issueKey)
+		watchers, _ := client.GetWatchers(ctx, issueKey)
+		fields, _ := cache.GetFieldsCacheFirst(ctx, client)
+		dctx := &jtkpresent.DetailContext{
```
Comment (monit-reviewer) [inline tools/jtk/internal/cmd/issues/get.go:91]: 🔵 **Low** (harness-engineering:harness-enforcement-reviewer): GetWatchers error is silently discarded (`watchers, _ := ...`) while GetTransitions error is explicitly captured via TransitionsFailed. A network or permissions failure on the watchers endpoint renders as 'Watchers: -' with no indication of failure, inconsistent with the transitions degradation path.

*Reply to this thread when addressed.*

File: tools/jtk/internal/present/issue.go [hunk 6]
```diff
@@ -238,8 +252,235 @@ func issueDescriptionSection(issue *api.Issue, fulltext bool) []present.Section
 	}
```
Comment (monit-reviewer) [inline tools/jtk/internal/present/issue.go:252]: 🔵 **Low** (harness-engineering:harness-self-documenting-code-reviewer): PresentDetailExtended discards the issue URL parameter (`_ string`). PresentDetail and PresentDetailProjection both surface the issue URL as a clickable/copy-pasteable link; the extended view silently omits it, making it the only detail-rendering path without a URL.

*Reply to this thread when addressed.*

File: tools/jtk/internal/present/issue.go [hunk 7]
```diff
@@ -238,8 +252,235 @@ func issueDescriptionSection(issue *api.Issue, fulltext bool) []present.Section
...
+			}
+			val := api.FormatCustomFieldValue(raw)
+			if val != "" {
+				parts = append(parts, fmt.Sprintf("%s=%s", id, val))
+			}
+		}
+		if len(parts) > 0 {
+			sort.Strings(parts)
+			customFieldsVal = strings.Join(parts, "; ")
+		}
```
Comment (monit-reviewer) [inline tools/jtk/internal/present/issue.go:472]: 🔵 **Low** (harness-engineering:harness-knowledge-reviewer): issueExtendedCustomFields emits individual message sections for each custom field with no section header or blank-line separator. They appear as an unlabeled block between Resolution and Description, making extended output hard to visually parse. Compare Transitions, which prepends an explicit 'Transitions:' label.

*Reply to this thread when addressed.*

File: tools/jtk/internal/cmd/issues/field_options.go [hunk 8]
```diff
@@ -15,27 +15,45 @@ import (
...
+				if issueFlag != "" {
+					issueKey = issueFlag
+				}
+			}
+			return runFieldOptions(cmd.Context(), opts, fieldNameOrID, issueKey)
 		},
 	}
 
-	cmd.Flags().StringVar(&issueKey, "issue", "", "Issue key for context-specific options (recommended)")
+	cmd.Flags().StringVar(&issueFlag, "issue", "", "Issue key for context-specific options (deprecated: use positional arg)")
```
Comment (monit-reviewer) [inline tools/jtk/internal/cmd/issues/field_options.go]: 🔵 **Low** (harness-engineering:harness-architecture-reviewer): The --issue flag is hidden with MarkHidden but not deprecated with MarkDeprecated. MarkDeprecated emits a visible warning when the flag is used, guiding users to migrate to the new positional-arg form. MarkHidden alone silently removes discoverability with no migration guidance.

*Reply to this thread when addressed.*

File: tools/jtk/api/issues.go [hunk 9]
```diff
@@ -179,6 +181,263 @@ func ParseEditMeta(fieldsData map[string]any) []EditFieldMeta {
...
+		return i.Fields.Parent.Key
+	},
+	"resolution": func(i *Issue) string {
+		if i.Fields.Resolution == nil {
+			return ""
+		}
+		return i.Fields.Resolution.Name
+	},
+	"fixVersions": func(i *Issue) string { return versionNames(i.Fields.FixVersions) },
+}
```
Comment (monit-reviewer) [inline tools/jtk/api/issues.go:355]: 🔵 **Low** (harness-engineering:harness-enforcement-reviewer): FormatCustomFieldValue converts float64 to int via `int(val)`. On 32-bit platforms int is 32-bit and would silently overflow for large values; even on 64-bit platforms float64 loses integer precision beyond 2^53. Use `int64` with an explicit comparison: `if val == float64(int64(val)) { return fmt.Sprintf("%d", int64(val)) }`.

*Reply to this thread when addressed.*

File: tools/jtk/api/issues.go [hunk 10]
```diff
@@ -179,6 +181,263 @@ func ParseEditMeta(fieldsData map[string]any) []EditFieldMeta {
...
+func versionNames(vs []Version) string {
+	if len(vs) == 0 {
+		return ""
+	}
+	names := make([]string, len(vs))
+	for i, v := range vs {
+		names[i] = v.Name
+	}
+	return strings.Join(names, ", ")
+}
```
Comment (monit-reviewer) [inline tools/jtk/api/issues.go:391]: 🔵 **Low** (harness-engineering:harness-self-documenting-code-reviewer): In the []any branch of FormatCustomFieldValue, array items that are map[string]any but contain neither 'value' nor 'name' key are silently dropped rather than falling back to fmt.Sprintf. A multi-select custom field with unexpected map shapes produces a truncated output string with no indication of missing items.

*Reply to this thread when addressed.*

File: tools/jtk/internal/cmd/issues/field_options_test.go [hunk 11]
```diff
@@ -95,3 +95,51 @@ func TestRunFieldOptions_CacheMiss_FallsBackToLive(t *testing.T) {
 		t.Fatal("expected live /field call on cache miss")
 	}
 }
```
Comment (monit-reviewer) [inline tools/jtk/internal/cmd/issues/field_options_test.go:97]: 🔵 **Low** (harness-engineering:harness-enforcement-reviewer): TestRunFieldOptions_FallbackToContext is missing t.Parallel(), unlike every other test in the file. It writes to the global cache via seedCacheForIssues and cache.WriteResource; running it serially while other tests run in parallel creates an intermittent data-race risk depending on test ordering.

*Reply to this thread when addressed.*

File: tools/jtk/internal/cmd/issues/field_options_test.go [hunk 12]
```diff
@@ -95,3 +95,51 @@ func TestRunFieldOptions_CacheMiss_FallsBackToLive(t *testing.T) {
...
+	testutil.RequireNoError(t, err)
+
+	var stdout bytes.Buffer
+	opts := &root.Options{Output: "table", Stdout: &stdout, Stderr: &bytes.Buffer{}}
+	opts.SetAPIClient(client)
+
+	err = runFieldOptions(context.Background(), opts, "Team", "TEST-1")
+	testutil.RequireNoError(t, err)
+	testutil.Contains(t, stdout.String(), "Platform")
+	testutil.Contains(t, stdout.String(), "Integration")
```
Comment (monit-reviewer) [inline tools/jtk/internal/cmd/issues/field_options_test.go:143]: 🔵 **Low** (harness-engineering:harness-enforcement-reviewer): The assertion `testutil.Contains(t, stdout.String(), "DISABLED")` only confirms the column header is present. Both fixture options have disabled=false, so the 'yes' rendering path in PresentFieldOptionsWithHeader is never exercised. A second fixture with a disabled option is needed to make this assertion meaningful.

*Reply to this thread when addressed.*

File: tools/jtk/internal/cmd/issues/fields_test.go [hunk 13]
```diff
@@ -73,6 +74,75 @@ func TestRunGlobalFields_CacheHit_CustomFilter_SkipsLiveCall(t *testing.T) {
 	testutil.NotContains(t, stdout.String(), "Summary")
```
Comment (monit-reviewer) [inline tools/jtk/internal/cmd/issues/fields_test.go:74]: 🔵 **Low** (harness-engineering:harness-knowledge-reviewer): TestRunIssueFields_ShowsFieldValues and TestRunIssueFields_CustomOnly are both missing t.Parallel(), inconsistent with surrounding tests that share the same cache-writing setup. This creates a data-race risk against parallel tests that also write the 'fields' cache entry.

*Reply to this thread when addressed.*

**Review by monit-reviewer — DISMISSED** [review]
## Automated PR Review



**Reviewed commit:** `4ad7efd`

### Summary

| Reviewer | Findings |
|----------|----------|
| harness-engineering:harness-architecture-reviewer | 2 |
| harness-engineering:harness-enforcement-reviewer | 5 |
| harness-engineering:harness-knowledge-reviewer | 3 |
| harness-engineering:harness-self-documenting-code-reviewer | 2 |
| security:security-code-auditor | 1 |

<details>
<summary><strong>harness-engineering:harness-architecture-reviewer (2 findings)</strong></summary>

**⚠️ Should Fix** - `tools/jtk/api/fields.go:254`
> ResolveFieldOptions falls through to context/global tiers when editErr is nil but opts is empty. A field that genuinely has zero configured options in edit meta will trigger two unnecessary extra API calls and may return options from a broader context that are invalid for the issue's project. The condition should distinguish 'field absent from edit meta' (fall through) from 'field present with no options' (return empty).

**💡 Suggestion** - `tools/jtk/internal/cmd/issues/field_options.go:55`
> The --issue flag is hidden with MarkHidden but not deprecated with MarkDeprecated. MarkDeprecated emits a visible warning when the flag is used, guiding users to migrate to the new positional-arg form. MarkHidden alone silently removes discoverability with no migration guidance.

</details>

<details>
<summary><strong>harness-engineering:harness-enforcement-reviewer (5 findings)</strong></summary>

**⚠️ Should Fix** - `tools/jtk/internal/cmd/issues/archive.go:40`
> Two compounding bugs in failure detection: (1) failedKeys is keyed on ae.IssueIdsOrKeys values from the API, which may be numeric IDs (e.g. '10042') rather than user-supplied keys (e.g. 'TEST-1'), so the lookup on line 48 never matches and all keys appear successful even on partial failure; (2) result.NumberUpdated is ignored entirely, so a no-op archive (all issues already archived, NumberUpdated=0, empty Errors) reports all input keys as successfully archived.

**💡 Suggestion** - `tools/jtk/internal/cmd/issues/get.go:91`
> GetWatchers error is silently discarded (`watchers, _ := ...`) while GetTransitions error is explicitly captured via TransitionsFailed. A network or permissions failure on the watchers endpoint renders as 'Watchers: -' with no indication of failure, inconsistent with the transitions degradation path.

**💡 Suggestion** - `tools/jtk/api/issues.go:354`
> FormatCustomFieldValue converts float64 to int via `int(val)`. On 32-bit platforms int is 32-bit and would silently overflow for large values; even on 64-bit platforms float64 loses integer precision beyond 2^53. Use `int64` with an explicit comparison: `if val == float64(int64(val)) { return fmt.Sprintf("%d", int64(val)) }`.

**💡 Suggestion** - `tools/jtk/internal/cmd/issues/field_options_test.go:97`
> TestRunFieldOptions_FallbackToContext is missing t.Parallel(), unlike every other test in the file. It writes to the global cache via seedCacheForIssues and cache.WriteResource; running it serially while other tests run in parallel creates an intermittent data-race risk depending on test ordering.

**💡 Suggestion** - `tools/jtk/internal/cmd/issues/field_options_test.go:143`
> The assertion `testutil.Contains(t, stdout.String(), "DISABLED")` only confirms the column header is present. Both fixture options have disabled=false, so the 'yes' rendering path in PresentFieldOptionsWithHeader is never exercised. A second fixture with a disabled option is needed to make this assertion meaningful.

</details>

<details>
<summary><strong>harness-engineering:harness-knowledge-reviewer (3 findings)</strong></summary>

**⚠️ Should Fix** - `tools/jtk/api/issues.go:251`
> Description truncation uses byte-slice indexing (`t[:80]`) rather than rune-aware slicing. For descriptions containing multi-byte UTF-8 characters whose boundary falls inside the first 80 bytes, this produces garbled output or panics with an invalid slice index. Use `[]rune(t)[:80]` or a utf8-aware trim.

**💡 Suggestion** - `tools/jtk/internal/present/issue.go:472`
> issueExtendedCustomFields emits individual message sections for each custom field with no section header or blank-line separator. They appear as an unlabeled block between Resolution and Description, making extended output hard to visually parse. Compare Transitions, which prepends an explicit 'Transitions:' label.

**💡 Suggestion** - `tools/jtk/internal/cmd/issues/fields_test.go:74`
> TestRunIssueFields_ShowsFieldValues and TestRunIssueFields_CustomOnly are both missing t.Parallel(), inconsistent with surrounding tests that share the same cache-writing setup. This creates a data-race risk against parallel tests that also write the 'fields' cache entry.

</details>

<details>
<summary><strong>harness-engineering:harness-self-documenting-code-reviewer (2 findings)</strong></summary>

**💡 Suggestion** - `tools/jtk/internal/present/issue.go:252`
> PresentDetailExtended discards the issue URL parameter (`_ string`). PresentDetail and PresentDetailProjection both surface the issue URL as a clickable/copy-pasteable link; the extended view silently omits it, making it the only detail-rendering path without a URL.

**💡 Suggestion** - `tools/jtk/api/issues.go:390`
> In the []any branch of FormatCustomFieldValue, array items that are map[string]any but contain neither 'value' nor 'name' key are silently dropped rather than falling back to fmt.Sprintf. A multi-select custom field with unexpected map shapes produces a truncated output string with no indication of missing items.

</details>

<details>
<summary><strong>security:security-code-auditor (1 findings)</strong></summary>

**💡 Suggestion** - `tools/jtk/api/fields.go:286`
> getAllContextOptions interpolates fieldID and contextID directly via fmt.Sprintf without url.PathEscape. Every other URL construction in this package escapes dynamic segments (e.g. GetIssueEditMeta, GetWatchers). While current Jira field and context IDs are safe, this is inconsistent and fragile.

</details>

*4 info-level observations excluded. Run with `--verbose` to include.*

*5 PR discussion threads considered.*

---
<details>
<summary>Completed in 4m 40s | $1.52</summary>

| Field | Value |
|---|---|
| Reviewers | hybrid-synthesis, harness-engineering:harness-architecture-reviewer, harness-engineering:harness-enforcement-reviewer, harness-engineering:harness-knowledge-reviewer, harness-engineering:harness-self-documenting-code-reviewer, security:security-code-auditor |
| Engine | claude |
| Reviewed by | [pr-review-daemon](https://github.com/SignalFT/pr-review-daemon) · [monit-pr-reviewer](https://github.com/apps/monit-pr-reviewer) |
| Duration | 4m 40s wall · 10m 49s compute (Reviewers: 2m 07s · Synthesis: 2m 30s) |
| Cost | $1.52 |
| Tokens | 377.2k in / 40.1k out |
| Turns | 14 |

</details>

File: tools/jtk/api/fields.go (hunk 1 above)
Comment (rianjs) [reply tools/jtk/api/fields.go:255]: Fixed — edit meta now returns immediately on success (even empty), only falls through when field absent (ErrFieldNotInEditMeta).

File: tools/jtk/internal/cmd/issues/archive.go (hunk 2 above)
Comment (rianjs) [reply tools/jtk/internal/cmd/issues/archive.go:41]: Fixed — success derivation now uses NumberUpdated > 0 as primary gate. Only cross-references error keys when NumberUpdated > 0 with errors present.

File: tools/jtk/api/issues.go (hunk 3 above)
Comment (rianjs) [reply tools/jtk/api/issues.go:251]: Fixed — now uses rune-aware slicing via []rune(t)[:80].

File: tools/jtk/api/fields.go (hunk 4 above)
Comment (rianjs) [reply tools/jtk/api/fields.go:289]: Fixed — getAllContextOptions now uses url.PathEscape for fieldID and contextID.

File: tools/jtk/internal/cmd/issues/get.go (hunk 5 above)
Comment (rianjs) [reply tools/jtk/internal/cmd/issues/get.go:91]: Acknowledged — watchers gracefully degrade to "-" by design since the watchers endpoint may not be available with bearer auth.

File: tools/jtk/internal/present/issue.go (hunk 6 above)
Comment (rianjs) [reply tools/jtk/internal/present/issue.go:252]: Acknowledged — PresentDetail also discards the URL parameter. The URL is not rendered in any text output path.

File: tools/jtk/internal/present/issue.go (hunk 7 above)
Comment (rianjs) [reply tools/jtk/internal/present/issue.go:472]: Acknowledged — custom fields block is unlabeled per spec format.

File: tools/jtk/internal/cmd/issues/field_options.go (hunk 8 above)
Comment (rianjs) [reply tools/jtk/internal/cmd/issues/field_options.go]: Fixed — changed from MarkHidden to MarkDeprecated with migration guidance.

File: tools/jtk/api/issues.go (hunk 9 above)
Comment (rianjs) [reply tools/jtk/api/issues.go:355]: Fixed — now uses int64 for the float64→integer conversion.

File: tools/jtk/api/issues.go (hunk 10 above)
Comment (rianjs) [reply tools/jtk/api/issues.go:391]: Acknowledged — silently dropping unrecognized map items avoids noisy output for internal Jira metadata.

File: tools/jtk/internal/cmd/issues/field_options_test.go (hunk 11 above)
Comment (rianjs) [reply tools/jtk/internal/cmd/issues/field_options_test.go:97]: Acknowledged — test uses seedCacheForIssues which is documented as non-parallel.

File: tools/jtk/internal/cmd/issues/field_options_test.go (hunk 12 above)
Comment (rianjs) [reply tools/jtk/internal/cmd/issues/field_options_test.go:143]: Acknowledged — test verifies the DISABLED column header presence, confirming the 3-column format change.

File: tools/jtk/internal/cmd/issues/fields_test.go (hunk 13 above)
Comment (rianjs) [reply tools/jtk/internal/cmd/issues/fields_test.go:74]: Acknowledged — intentionally non-parallel, consistent with existing cache-writing test pattern.

File: tools/jtk/api/fields.go (hunk 1 above)
Comment (monit-reviewer) [reply tools/jtk/api/fields.go:255]: **Settled**: monit-reviewer flagged that ResolveFieldOptions fell through to broader context tiers when edit meta returned empty options, causing unnecessary API calls and potentially invalid results. rianjs fixed it so edit meta returns immediately on success (even empty), only falling through when the field is absent (ErrFieldNotInEditMeta).

File: tools/jtk/internal/cmd/issues/archive.go (hunk 2 above)
Comment (monit-reviewer) [reply tools/jtk/internal/cmd/issues/archive.go:41]: **Settled**: monit-reviewer identified two bugs in archive failure detection: ID/key mismatch in failedKeys lookup and ignoring NumberUpdated. rianjs fixed success derivation to use NumberUpdated > 0 as the primary gate, only cross-referencing error keys when partial failures are present.

File: tools/jtk/api/issues.go (hunk 3 above)
Comment (monit-reviewer) [reply tools/jtk/api/issues.go:251]: **Settled**: monit-reviewer flagged that description truncation used byte-slice indexing which could garble or panic on multi-byte UTF-8 characters. rianjs fixed it to use rune-aware slicing via []rune(t)[:80].

File: tools/jtk/api/fields.go (hunk 4 above)
Comment (monit-reviewer) [reply tools/jtk/api/fields.go:289]: **Settled**: monit-reviewer noted that getAllContextOptions interpolated fieldID and contextID without url.PathEscape, inconsistent with the rest of the package. rianjs fixed it to use url.PathEscape for both parameters.

File: tools/jtk/internal/cmd/issues/get.go (hunk 5 above)
Comment (monit-reviewer) [reply tools/jtk/internal/cmd/issues/get.go:91]: **Settled**: monit-reviewer flagged that GetWatchers errors were silently discarded, inconsistent with the transitions degradation path. rianjs acknowledged this is intentional design since the watchers endpoint may not be available with bearer auth, gracefully degrading to '-'.

File: tools/jtk/internal/present/issue.go (hunk 6 above)
Comment (monit-reviewer) [reply tools/jtk/internal/present/issue.go:252]: **Settled**: monit-reviewer noted that PresentDetailExtended discards the issue URL parameter, unlike other detail-rendering paths. rianjs clarified that PresentDetail also discards the URL and it is not rendered in any text output path.

File: tools/jtk/internal/present/issue.go (hunk 7 above)
Comment (monit-reviewer) [reply tools/jtk/internal/present/issue.go:472]: **Settled**: monit-reviewer flagged that custom fields in extended output appear as an unlabeled block with no section header. rianjs acknowledged this is intentional per the spec format.

File: tools/jtk/internal/cmd/issues/field_options.go (hunk 8 above)
Comment (monit-reviewer) [reply tools/jtk/internal/cmd/issues/field_options.go]: **Settled**: monit-reviewer noted that the --issue flag used MarkHidden instead of MarkDeprecated, providing no migration guidance to users. rianjs fixed it by switching to MarkDeprecated with migration guidance.

File: tools/jtk/api/issues.go (hunk 9 above)
Comment (monit-reviewer) [reply tools/jtk/api/issues.go:355]: **Settled**: monit-reviewer flagged that float64-to-int conversion in FormatCustomFieldValue could overflow on 32-bit platforms and lose precision beyond 2^53. rianjs fixed it to use int64 for the conversion.

File: tools/jtk/api/issues.go (hunk 10 above)
Comment (monit-reviewer) [reply tools/jtk/api/issues.go:391]: **Settled**: monit-reviewer noted that unrecognized map shapes in the []any branch of FormatCustomFieldValue are silently dropped with no indication of missing items. rianjs acknowledged this is intentional to avoid noisy output for internal Jira metadata.

File: tools/jtk/internal/cmd/issues/field_options_test.go (hunk 11 above)
Comment (monit-reviewer) [reply tools/jtk/internal/cmd/issues/field_options_test.go:97]: **Settled**: monit-reviewer flagged that TestRunFieldOptions_FallbackToContext is missing t.Parallel(), creating a potential data-race risk. rianjs acknowledged this is intentional as the test uses seedCacheForIssues which is documented as non-parallel.

File: tools/jtk/internal/cmd/issues/field_options_test.go (hunk 12 above)
Comment (monit-reviewer) [reply tools/jtk/internal/cmd/issues/field_options_test.go:143]: **Settled**: monit-reviewer noted that the DISABLED column assertion only checks for the header, never exercising the 'yes' rendering path since both fixtures have disabled=false. rianjs acknowledged the test is intentionally verifying the 3-column format change via header presence.

File: tools/jtk/internal/cmd/issues/fields_test.go (hunk 13 above)
Comment (monit-reviewer) [reply tools/jtk/internal/cmd/issues/fields_test.go:74]: **Settled**: monit-reviewer flagged that two tests are missing t.Parallel(), creating a data-race risk against parallel cache-writing tests. rianjs acknowledged this is intentional, consistent with the existing non-parallel cache-writing test pattern.

File: tools/jtk/internal/cmd/issues/archive.go [hunk 14]
```diff
@@ -0,0 +1,80 @@
...
+	for _, ae := range result.Errors {
+		fmt.Fprintf(opts.Stderr, "Archive error: %s (%s)\n", ae.Message, strings.Join(ae.IssueIdsOrKeys, ", "))
+	}
+
+	var successKeys []string
+	if result.NumberUpdated > 0 && !hasErrors {
+		successKeys = keys
+	} else if result.NumberUpdated > 0 {
+		failedIDs := make(map[string]bool)
+		for _, ae := range result.Errors {
```
Comment (monit-reviewer) [inline tools/jtk/internal/cmd/issues/archive.go:62]: 🟡 **Medium** (harness-engineering:harness-architecture-reviewer): When result.NumberUpdated > 0 and hasErrors is false, successKeys is assigned the full input slice regardless of whether NumberUpdated equals len(keys). If the Jira bulk archive API returns a count lower than the submitted key count with an empty errors map (e.g. already-archived issues silently skipped), all input keys are reported as successfully archived. The fix correctly gates on NumberUpdated > 0 for the happy path, but does not validate that the count matches.

*Reply to this thread when addressed.*

File: tools/jtk/api/fields.go [hunk 15]
```diff
@@ -250,3 +252,62 @@ func (c *Client) GetFieldOptionsFromEditMeta(ctx context.Context, issueKey, fiel
...
+
+// ResolveFieldOptions returns allowed values for a field in the context of a
+// specific issue. It uses a three-tier resolution strategy:
+//  1. Edit metadata (reliable for editable fields, already project-scoped)
+//  2. Default field context + context options (handles read-only custom fields)
+//  3. Global field options (last resort)
+func ResolveFieldOptions(ctx context.Context, c *Client, issueKey, fieldID string) ([]FieldOptionValue, error) {
+	opts, editErr := c.GetFieldOptionsFromEditMeta(ctx, issueKey, fieldID)
+	if editErr == nil {
+		return opts, nil
```
Comment (monit-reviewer) [inline tools/jtk/api/fields.go:264]: 🟡 **Medium** (harness-engineering:harness-enforcement-reviewer): In ResolveFieldOptions, a non-nil error from getAllContextOptions (tier 2) is silently discarded and execution falls through to the global tier 3 path. A permission or transient network error on the context endpoint is treated identically to 'field has no context options', causing the caller to receive stale global options rather than an error. The tier-2 error should be propagated when ctxErr is nil but pageErr is non-nil.

*Reply to this thread when addressed.*

File: tools/jtk/internal/cmd/issues/archive.go [hunk 16]
```diff
@@ -0,0 +1,80 @@
...
+	}
+
+	result, err := client.ArchiveIssues(ctx, keys)
+	if err != nil {
+		return err
+	}
+
+	hasErrors := len(result.Errors) > 0
+	for _, ae := range result.Errors {
+		fmt.Fprintf(opts.Stderr, "Archive error: %s (%s)\n", ae.Message, strings.Join(ae.IssueIdsOrKeys, ", "))
```
Comment (monit-reviewer) [inline tools/jtk/internal/cmd/issues/archive.go:51]: 🔵 **Low** (harness-engineering:harness-architecture-reviewer): Iteration over result.Errors (map[string]ArchiveError) is non-deterministic in Go. When multiple error categories are returned, the order of error lines written to stderr varies between runs, making scripted parsing of archive failure output unreliable. Sort error keys before iterating.

*Reply to this thread when addressed.*

File: tools/jtk/internal/cmd/issues/archive.go [hunk 17]
```diff
@@ -0,0 +1,80 @@
...
+	}
```
Comment (monit-reviewer) [inline tools/jtk/internal/cmd/issues/archive.go:52]: 🔵 **Low** (harness-engineering:harness-architecture-reviewer): When result.NumberUpdated == 0 and the errors map is empty (e.g. all submitted issues were already archived and the API treats the call as a no-op), successKeys remains nil, no output is written, and nil is returned. The caller sees a blank response with exit 0 and no indication that the operation had no effect.

*Reply to this thread when addressed.*

File: tools/jtk/internal/present/field.go [hunk 18]
```diff
@@ -342,23 +361,19 @@ func (FieldPresenter) PresentFieldOptionsWithHeader(fieldName string, options []
 		if value == "" {
```
Comment (monit-reviewer) [inline tools/jtk/internal/present/field.go:361]: 🔵 **Low** (harness-engineering:harness-knowledge-reviewer): PresentFieldOptionsWithHeader removes the 'Allowed values for field X:' info header and adds a DISABLED column, changing the output format from ID|VALUE to ID|VALUE|DISABLED. This is a backward-incompatible change: existing scripts parsing the two-column table or the header line will break silently. The field name is also no longer surfaced in the rendered output header, removing context when output is piped.

*Reply to this thread when addressed.*

**Review by monit-reviewer — DISMISSED** [review]
## Automated PR Review



**Reviewed commit:** `4ea31de` | **Previous:** `4ad7efd` (incremental)

### Summary

| Reviewer | Findings |
|----------|----------|
| harness-engineering:harness-architecture-reviewer | 3 |
| harness-engineering:harness-enforcement-reviewer | 1 |
| harness-engineering:harness-knowledge-reviewer | 1 |

<details>
<summary><strong>harness-engineering:harness-architecture-reviewer (3 findings)</strong></summary>

**⚠️ Should Fix** - `tools/jtk/internal/cmd/issues/archive.go:51`
> When result.NumberUpdated > 0 and hasErrors is false, successKeys is assigned the full input slice regardless of whether NumberUpdated equals len(keys). If the Jira bulk archive API returns a count lower than the submitted key count with an empty errors map (e.g. already-archived issues silently skipped), all input keys are reported as successfully archived. The fix correctly gates on NumberUpdated > 0 for the happy path, but does not validate that the count matches.

**💡 Suggestion** - `tools/jtk/internal/cmd/issues/archive.go:43`
> Iteration over result.Errors (map[string]ArchiveError) is non-deterministic in Go. When multiple error categories are returned, the order of error lines written to stderr varies between runs, making scripted parsing of archive failure output unreliable. Sort error keys before iterating.

**💡 Suggestion** - `tools/jtk/internal/cmd/issues/archive.go:44`
> When result.NumberUpdated == 0 and the errors map is empty (e.g. all submitted issues were already archived and the API treats the call as a no-op), successKeys remains nil, no output is written, and nil is returned. The caller sees a blank response with exit 0 and no indication that the operation had no effect.

</details>

<details>
<summary><strong>harness-engineering:harness-enforcement-reviewer (1 findings)</strong></summary>

**⚠️ Should Fix** - `tools/jtk/api/fields.go:264`
> In ResolveFieldOptions, a non-nil error from getAllContextOptions (tier 2) is silently discarded and execution falls through to the global tier 3 path. A permission or transient network error on the context endpoint is treated identically to 'field has no context options', causing the caller to receive stale global options rather than an error. The tier-2 error should be propagated when ctxErr is nil but pageErr is non-nil.

</details>

<details>
<summary><strong>harness-engineering:harness-knowledge-reviewer (1 findings)</strong></summary>

**💡 Suggestion** - `tools/jtk/internal/present/field.go:361`
> PresentFieldOptionsWithHeader removes the 'Allowed values for field X:' info header and adds a DISABLED column, changing the output format from ID|VALUE to ID|VALUE|DISABLED. This is a backward-incompatible change: existing scripts parsing the two-column table or the header line will break silently. The field name is also no longer surfaced in the rendered output header, removing context when output is piped.

</details>

*6 info-level observations excluded. Run with `--verbose` to include.*

*18 PR discussion threads considered.*

---
<details>
<summary>Completed in 5m 06s | $1.64</summary>

| Field | Value |
|---|---|
| Mode | Re-review · Cycle 2 · Session resumed |
| Reviewers | hybrid-synthesis, harness-engineering:harness-architecture-reviewer, harness-engineering:harness-enforcement-reviewer, harness-engineering:harness-knowledge-reviewer, harness-engineering:harness-self-documenting-code-reviewer, security:security-code-auditor |
| Engine | claude |
| Reviewed by | [pr-review-daemon](https://github.com/SignalFT/pr-review-daemon) · [monit-pr-reviewer](https://github.com/apps/monit-pr-reviewer) |
| Duration | 5m 06s wall · 12m 26s compute (Reviewers: 2m 25s · Synthesis: 2m 05s) |
| Cost | $1.64 |
| Tokens | 421.9k in / 50.0k out |
| Turns | 17 |

</details>

**Comment by rianjs** [comment]
These are low-value, please approve the PR

**Review by monit-reviewer — APPROVED** [review]
## Automated PR Review



**Reviewed commit:** `63d880c`

### Human Override

Approved at the request of @rianjs ([comment](https://github.com/open-cli-collective/atlassian-cli/pull/292#issuecomment-4323098088)).

> These are low-value, please approve the PR

No automated reviewers were run.
