### PR TITLE
feat(jtk): fix links list --extended column order

### LINKED ISSUE #289: jtk links: fix list --extended column order
Parent: #230

### `jtk links list <key> --extended`
**Current:** `TYPE_ID` and `STATUS` columns are at the tail of the row.
**Expected:** `TYPE_ID` second (after `LINK_ID`), `STATUS` before `SUMMARY`:
```
LINK_ID | TYPE_ID | TYPE | DIRECTION | ISSUE | STATUS | SUMMARY
17844 | 10100 | Blocker | blocks | MON-4819 | Backlog | Linked issue B
17845 | 10200 | Relates | relates to | MON-4700 | Deployed | Fix ghost row in data table
```

See #230 for full spec.

### PR DESCRIPTION
**Pull request by rianjs**
## Summary
- Reorders `jtk links list --extended` columns to match #230 spec
- Before: `LINK_ID | TYPE | DIRECTION | ISSUE | SUMMARY | TYPE_ID | STATUS`
- After: `LINK_ID | TYPE_ID | TYPE | DIRECTION | ISSUE | STATUS | SUMMARY`

Closes #289

## Test plan
- [x] Spec-lock test verifies header order for both default and extended modes
- [x] Extended test asserts exact header order and cell positions for TYPE_ID, STATUS, SUMMARY
- [x] `make build && make test && make lint` all pass

### CODE REVIEW

**Comment by rianjs** [comment]
**Blocker**
- None.

**Major**
- None.

**Minor**
- None.

**Nit**
- None.

**Comment by rianjs** [comment]
## Test coverage review

### What's covered well
- Header order is spec-locked in `TestLinkPresenter_PresentList_Extended` (full slice comparison + per-index check)
- `TestLinkListSpec_MatchesPresentListHeaders` catches any future drift between `LinkListSpec` and the hardcoded `headers` slice in `PresentList`
- Cell count guard (`t.Fatalf`) prevents silent index-out-of-range panics

### Gaps

**1. Inward issue path not tested in extended mode**
`TestLinkPresenter_PresentList_Extended` uses `OutwardIssue` only. The `InwardIssue` branch has different direction logic (`l.Type.Outward` vs `l.Type.Inward`) and its own nil-status guard. A reordering bug in the inward branch would go undetected.

**2. Nil status in extended mode not covered**
The new column order puts STATUS at index 5. If `Status == nil`, `OrDash` should emit `"-"` there. No test exercises this path with the new ordering — the only extended test fixture has a non-nil status.

**3. Cells[2]–[4] not asserted**
`TestLinkPresenter_PresentList_Extended` skips `TYPE` (index 2), `DIRECTION` (index 3), and `ISSUE` (index 4). A transposition between those three columns (e.g. direction/issue swap) would not be caught.

**4. Default (non-extended) cell order not asserted anywhere**
`TestLinkListSpec_MatchesPresentListHeaders` checks header/spec alignment for both modes but never reads `row.Cells`. A cell-order regression in the non-extended branch has no test.

### Suggested additions
- Extended test with `InwardIssue` + nil status: verify `row.Cells[3]` (DIRECTION uses `Outward`), `row.Cells[5]` is `"-"`, `row.Cells[6]` is the summary
- Assert all 7 cells in the existing extended test (or a table-driven variant)
- One non-extended row assertion covering all 5 cell positions

File: tools/jtk/internal/present/link_test.go [hunk 1]
```diff
@@ -64,6 +64,73 @@ func TestLinkTypesSpec_MatchesPresentTypesHeaders(t *testing.T) {
...
+	}
+	for i, h := range expectedHeaders {
+		if table.Headers[i] != h {
+			t.Errorf("header[%d]: expected %q, got %q", i, h, table.Headers[i])
+		}
+	}
+
+	for i, row := range table.Rows {
+		if len(row.Cells) != len(expectedHeaders) {
+			t.Fatalf("row %d: expected %d cells, got %d", i, len(expectedHeaders), len(row.Cells))
```
Comment (monit-reviewer) [inline tools/jtk/internal/present/link_test.go:110]: 🔵 **Low** (harness-engineering:harness-enforcement-reviewer): TestLinkPresenter_PresentList_Extended asserts direction = "is blocked by" (the Inward label) for a link where OutwardIssue is set and Type.Outward = "blocks". If OutwardIssue should render the Outward label per Jira semantics, this test locks in a pre-existing direction-inversion bug. The direction logic was not changed in this PR, but this is the first assertion covering concrete direction values — worth verifying the expected label against the Jira API contract before this test becomes the reference.

*Reply to this thread when addressed.*

**Review by monit-reviewer — APPROVED** [review]
## Automated PR Review



**Reviewed commit:** `7ce5f6e`

> **Approved** with 2 non-blocking suggestions below. Address at your discretion.

### Summary

| Reviewer | Findings |
|----------|----------|
| harness-engineering:harness-enforcement-reviewer | 1 |
| harness-engineering:harness-knowledge-reviewer | 1 |

<details>
<summary><strong>harness-engineering:harness-enforcement-reviewer (1 findings)</strong></summary>

**💡 Suggestion** - `tools/jtk/internal/present/link_test.go:110`
> TestLinkPresenter_PresentList_Extended asserts direction = "is blocked by" (the Inward label) for a link where OutwardIssue is set and Type.Outward = "blocks". If OutwardIssue should render the Outward label per Jira semantics, this test locks in a pre-existing direction-inversion bug. The direction logic was not changed in this PR, but this is the first assertion covering concrete direction values — worth verifying the expected label against the Jira API contract before this test becomes the reference.

</details>

<details>
<summary><strong>harness-engineering:harness-knowledge-reviewer (1 findings)</strong></summary>

**💡 Suggestion** - `tools/jtk/internal/present/link_test.go:144`
> TestLinkPresenter_PresentList_Default_CellOrder covers only OutwardIssue in default mode. InwardIssue in default mode is untested, leaving a cell-order coverage gap for the non-extended path. The author's own test review (PR comment) acknowledges the InwardIssue gap in extended mode; the same gap exists in default mode.

</details>

*2 PR discussion threads considered.*

---
<details>
<summary>Completed in 2m 16s | $0.63</summary>

| Field | Value |
|---|---|
| Reviewers | hybrid-synthesis, harness-engineering:harness-architecture-reviewer, harness-engineering:harness-enforcement-reviewer, harness-engineering:harness-knowledge-reviewer, harness-engineering:harness-self-documenting-code-reviewer, security:security-code-auditor |
| Engine | claude |
| Reviewed by | [pr-review-daemon](https://github.com/SignalFT/pr-review-daemon) · [monit-pr-reviewer](https://github.com/apps/monit-pr-reviewer) |
| Duration | 2m 16s wall · 6m 14s compute (Reviewers: 1m 47s · Synthesis: 27s) |
| Cost | $0.63 |
| Tokens | 217.5k in / 20.8k out |
| Turns | 16 |

</details>

*Note: Posted 1 inline comment. 1 finding remained in the summary because GitHub could not attach them to the current diff.*

File: tools/jtk/internal/present/link_test.go (hunk 1 above)
Comment (rianjs) [reply tools/jtk/internal/present/link_test.go:110]: Pre-existing behavior — when OutwardIssue is set, the link reads as 'this issue [Inward verb] that issue', so Inward label is correct. This matches the Jira API semantics and has been the convention since the links feature was added. Not in scope for this column-reorder PR.
