### PR TITLE
feat(jtk): fix dashboards list/gadgets output and wire --id/--extended flags

### LINKED ISSUE #284: jtk dashboards: fix list/gadgets output format and wire --id/--extended flags
Parent: #230

### `jtk dashboards list` (default)
**Current:** missing GADGETS column; column order differs.
**Expected:**
```
ID | GADGETS | OWNER | FAVOURITE | NAME
10072 | 4 | Rian Stockbower | yes | Team Dashboard
10069 | 2 | Rusty Hall | no | Incidents Overview
```

### `jtk dashboards list --id`
**Current:** flag not wired — output identical to default.
**Expected:** one ID per line.

### `jtk dashboards list --extended`
**Current:** flag not wired — output identical to default.
**Expected:**
```
ID | GADGETS | OWNER | FAVOURITE | RANK | PERMISSIONS | NAME
10072 | 4 | Rian Stockbower | yes | 0 | private | Team Dashboard
10069 | 2 | Rusty Hall | no | 1 | group:developers | Incidents Overview
```

### `jtk dashboards gadgets list <dashboardId>` (default)
**Current:** column `TYPE` renamed to `MODULE`; POSITION at tail; column order differs.
**Expected:**
```
ID | POSITION | TITLE | TYPE
10122 | 0,0 | Sprint Burndown | sprint-burndown-gadget
10123 | 0,1 | Created vs Resolved | created-vs-resolved-gadget
```

### `jtk dashboards gadgets list <dashboardId> --id`
**Current:** flag not wired — output identical to default.
**Expected:** one ID per line.

See #230 for full spec.

### PR DESCRIPTION
**Pull request by rianjs**
## Summary
- Fix `dashboards list` column order to `ID|GADGETS|OWNER|FAVOURITE|NAME` with gadget count fetching
- Wire `--id` flag for `dashboards list` and `gadgets list` (one ID per line, empty results emit nothing)
- Wire `--extended` flag for `dashboards list` adding `RANK|PERMISSIONS` columns
- Fix `gadgets list` column order to `ID|POSITION|TITLE|TYPE` (rename MODULE→TYPE, always show position including 0,0)
- Expand `SharePerm` type with Group/Project fields for permission display formatting
- Use `Emit`/`EmitIDs` helpers and `view.FormatJSON` constant throughout

Closes #284

## Test plan
- [x] `make build` — clean
- [x] `make test` — all passing
- [x] `make lint` — no new issues (pre-existing gosec in config.go only)
- [ ] Verify `jtk dashboards list` shows GADGETS column with counts
- [ ] Verify `jtk dashboards list --id` emits one ID per line
- [ ] Verify `jtk dashboards list --extended` shows RANK and PERMISSIONS
- [ ] Verify `jtk dashboards gadgets list <id>` shows ID|POSITION|TITLE|TYPE
- [ ] Verify `jtk dashboards gadgets list <id> --id` emits one ID per line

### CODE REVIEW

**Comment by rianjs** [comment]
No blocker or major findings. The implementation matches the agreed product shape: list/gadget column order, `--id` precedence, `--extended`, `Popularity` as `RANK`, create count `0`, and unknown gadget counts as `-`.

**Minor**
- `tools/jtk/internal/cmd/dashboards/dashboards_test.go`: the command-level output tests are still loose for an output-format PR. Assert exact header lines for `TestRunList_ColumnOrder`, `TestRunGadgetsList_ColumnOrder`, and exact stdout for `--id` cases (`10001\n10002\n`). The presenter tests lock order, but the command tests should also verify the rendered contract.

**Nit**
- `fetchGadgetCounts(_ context.Context, ...)` advertises a context parameter but intentionally ignores it. Either drop the parameter until the dashboard API is ctx-aware, or add a TODO in the comment so future readers don’t assume cancellation is honored.

**Comment by rianjs** [comment]
No findings.

The updated diff matches the agreed architecture and product intent: `RANK` maps to `Popularity`, `--id` takes precedence and emits exact ID lines, JSON avoids gadget-count side effects, create renders `GADGETS=0`, gadget output uses `ID|POSITION|TITLE|TYPE`, and the context tradeoff is now explicit.

**Comment by rianjs** [comment]
## TDD Assessment

**Overall: well-covered.** The PR adds substantial test surface alongside the feature additions. A few gaps worth flagging.

### Not tested that should be

**1.  partial-failure behavior**
The function silently skips dashboards where the gadget API call fails (continues without setting the key), so those entries render as `-`. No test covers this path — a test with a server that returns 500 for one dashboard ID and 200 for another would confirm the count map is correct for the successful ones and missing for the failed one. Given this is the main new I/O behavior in the list path, it's a gap worth closing.

**2. `--extended` + `--id` precedence**
`runList` checks `EmitIDOnly()` before `IsExtended()`, so `--id` wins. No test exercises both flags together to verify the precedence. The analogous `TestRunList_IDOnly` only sets `IDOnly` — adding a case where both are true and confirming only IDs are emitted would make the contract explicit.

**3. `--extended` in JSON mode**
`runList` takes the `v.Format == view.FormatJSON` branch before the `IsExtended()` check, so `--extended --output json` emits the same payload as plain JSON. That's probably intentional (raw API payload is already "extended"), but there's no test that hits `runList` with `{Output: "json", Extended: true}` to document this.

**4. `PresentListExtended` with nil counts / missing key**
`PresentList` has dedicated tests for nil counts and missing keys (`TestDashboardPresenter_PresentList_NilCounts`, `_MissingKey`). `PresentListExtended` has only the happy-path column-order test — the same nil/missing-key cases aren't covered for the extended variant.

**5. `formatPermissions` — project with nil `Project` field**
The `"project"` branch checks `p.Project != nil && p.Project.Key != ""` before appending the key. The test covers `{Type: "project"}` (nil Project pointer) but not `{Type: "project", Project: &SharePermProject{Key: ""}}` (non-nil pointer with empty key). Both should render `"project"` — the second case is distinct and easy to miss in a refactor.

### Not a concern

- Refactoring from manual `present.Render` + `fmt.Fprint` to `jtkpresent.Emit` is mechanical and well-covered by existing output-content assertions.
- New `SharePermGroup` / `SharePermProject` types are JSON-only additions with no logic to unit-test independently.
- `runCreate` hardcoding `counts[dash.ID] = 0` is correct (freshly created dashboard has no gadgets) and the assertion on `"0"" in `TestRunCreate` confirms it.

File: tools/jtk/internal/cmd/dashboards/dashboards_test.go [hunk 1]
```diff
@@ -39,15 +65,230 @@ func TestRunList(t *testing.T) {
...
+		w.WriteHeader(http.StatusNotFound)
+	}))
+	defer server.Close()
+
+	client, err := api.New(api.ClientConfig{URL: server.URL, Email: "t@t.com", APIToken: "tok"})
+	testutil.RequireNoError(t, err)
+
+	var stdout bytes.Buffer
+	opts := &root.Options{Output: "table", Stdout: &stdout, Stderr: &bytes.Buffer{}}
+	opts.SetAPIClient(client)
```
Comment (monit-reviewer) [inline tools/jtk/internal/cmd/dashboards/dashboards_test.go:222]: 🟡 **Medium** (harness-engineering:harness-enforcement-reviewer): TestRunList_GadgetFetchFails asserts `testutil.Contains(t, out, "-")` to verify the GADGETS cell renders "-" on fetch failure, but table rendering always produces horizontal separator lines made of dashes. This assertion passes vacuously regardless of whether the gadget count cell actually shows "-". The test should parse the data row and assert the specific column value to be meaningful.

*Reply to this thread when addressed.*

File: tools/jtk/internal/cmd/dashboards/dashboards.go [hunk 2]
```diff
@@ -93,23 +94,46 @@ func runList(_ context.Context, opts *root.Options, search string, maxResults in
...
-	_, _ = fmt.Fprint(opts.Stderr, out.Stderr)
-	return nil
+	gadgetCounts := fetchGadgetCounts(client, dashboards)
+
+	presenter := jtkpresent.DashboardPresenter{}
+	if opts.IsExtended() {
+		return jtkpresent.Emit(opts, presenter.PresentListExtended(dashboards, gadgetCounts))
+	}
+
+	return jtkpresent.Emit(opts, presenter.PresentList(dashboards, gadgetCounts))
```
Comment (monit-reviewer) [inline tools/jtk/internal/cmd/dashboards/dashboards.go:120]: 🟡 **Medium** (harness-engineering:harness-enforcement-reviewer): fetchGadgetCounts makes one sequential HTTP call per dashboard with no concurrency, no per-call timeout, and no context propagation (runList discards its context). With --max defaulting to 50, a single `dashboards list` issues up to 50 blocking API calls. A single slow or hung gadget endpoint stalls the entire command indefinitely — there is no deadline to bound the worst case. The comment acknowledges context deferral but not the indefinite-hang risk from an unresponsive upstream.

*Reply to this thread when addressed.*

File: tools/jtk/internal/cmd/dashboards/dashboards_test.go [hunk 3]
```diff
@@ -39,15 +65,230 @@ func TestRunList(t *testing.T) {
...
+			return
+		}
+		if strings.Contains(r.URL.Path, "/gadget") {
+			w.WriteHeader(http.StatusInternalServerError)
+			return
+		}
+		w.WriteHeader(http.StatusNotFound)
+	}))
+	defer server.Close()
+
```
Comment (monit-reviewer) [inline tools/jtk/internal/cmd/dashboards/dashboards_test.go:216]: 🔵 **Low** (harness-engineering:harness-architecture-reviewer): TestRunList_Extended asserts `testutil.Contains(t, out, "3")` for the RANK column, but the gadget count is also 3. If RANK rendering were broken the test would still pass as long as gadget count appears. Use a distinct value for Popularity (e.g. 7) to uniquely verify the RANK column.

*Reply to this thread when addressed.*

File: tools/jtk/internal/present/dashboard.go [hunk 4]
```diff
@@ -172,3 +200,42 @@ func (DashboardPresenter) PresentNoGadgets(dashboardID string) *present.OutputMo
...
+	if !ok {
+		return "-"
+	}
+	return FormatInt(n)
+}
+
+func formatPermissions(perms []api.SharePerm) string {
+	if len(perms) == 0 {
+		return "private"
+	}
```
Comment (monit-reviewer) [inline tools/jtk/internal/present/dashboard.go:218]: 🔵 **Low** (harness-engineering:harness-knowledge-reviewer): formatPermissions has no case for `projectRole`, `public`, or `authenticated` permission types that Jira returns. These fall through to the default branch and emit the raw API string, which is inconsistent with the explicit human-readable mappings for other types (e.g. `loggedin` → `logged-in`). Add cases or document which types are intentionally out of scope.

*Reply to this thread when addressed.*

File: tools/jtk/internal/cmd/dashboards/dashboards_test.go [hunk 5]
```diff
@@ -39,15 +65,230 @@ func TestRunList(t *testing.T) {
...
+	}
+	gadgets := map[string][]api.DashboardGadget{
+		"10001": {{ID: 1, Title: "G1"}, {ID: 2, Title: "G2"}},
+	}
+	server := newListTestServer(t, dashboards, gadgets)
+	defer server.Close()
+
+	client, err := api.New(api.ClientConfig{URL: server.URL, Email: "t@t.com", APIToken: "tok"})
+	testutil.RequireNoError(t, err)
+
```
Comment (monit-reviewer) [inline tools/jtk/internal/cmd/dashboards/dashboards_test.go:80]: 🔵 **Low** (harness-engineering:harness-knowledge-reviewer): TestRunList_ColumnOrder and TestRunGadgetsList_ColumnOrder use `strings.Index` on the rendered table header to compare column positions. Any future column whose name contains a substring of another (e.g. `ID` within a hypothetical `GADGET_ID`) would silently break ordering assertions. Asserting against the presenter's TableSection.Headers slice directly — as done in dashboard_test.go — is more robust.

*Reply to this thread when addressed.*

File: tools/jtk/internal/present/dashboard.go [hunk 6]
```diff
@@ -45,45 +46,72 @@ func (DashboardPresenter) PresentDetail(d *api.Dashboard, gadgets []api.Dashboar
...
-		}
+		pos := fmt.Sprintf("%d,%d", g.Position.Row, g.Position.Column)
 		rows[i] = present.Row{
-			Cells: []string{FormatInt(g.ID), g.Title, g.ModuleID, pos},
+			Cells: []string{FormatInt(g.ID), pos, g.Title, g.ModuleID},
 		}
 	}
 	return &present.OutputModel{
 		Sections: []present.Section{
 			&present.TableSection{
```
Comment (monit-reviewer) [inline tools/jtk/internal/present/dashboard.go:113]: 🔵 **Low** (harness-engineering:harness-self-documenting-code-reviewer): The gadget column header is renamed MODULE → TYPE, but the cell value is still `g.ModuleID` (a technical identifier like `com.atlassian.jira.gadgets:filter-results-gadget`). TYPE implies a short category label; what is displayed is a module identifier. MODULE was more accurate, and the rename may confuse users who see a long dotted string under a column labelled TYPE.

*Reply to this thread when addressed.*

**Review by monit-reviewer — DISMISSED** [review]
## Automated PR Review



**Reviewed commit:** `68ecd00`

### Summary

| Reviewer | Findings |
|----------|----------|
| harness-engineering:harness-architecture-reviewer | 1 |
| harness-engineering:harness-enforcement-reviewer | 2 |
| harness-engineering:harness-knowledge-reviewer | 2 |
| harness-engineering:harness-self-documenting-code-reviewer | 1 |

<details>
<summary><strong>harness-engineering:harness-architecture-reviewer (1 findings)</strong></summary>

**💡 Suggestion** - `tools/jtk/internal/cmd/dashboards/dashboards_test.go:216`
> TestRunList_Extended asserts `testutil.Contains(t, out, "3")` for the RANK column, but the gadget count is also 3. If RANK rendering were broken the test would still pass as long as gadget count appears. Use a distinct value for Popularity (e.g. 7) to uniquely verify the RANK column.

</details>

<details>
<summary><strong>harness-engineering:harness-enforcement-reviewer (2 findings)</strong></summary>

**⚠️ Should Fix** - `tools/jtk/internal/cmd/dashboards/dashboards_test.go:222`
> TestRunList_GadgetFetchFails asserts `testutil.Contains(t, out, "-")` to verify the GADGETS cell renders "-" on fetch failure, but table rendering always produces horizontal separator lines made of dashes. This assertion passes vacuously regardless of whether the gadget count cell actually shows "-". The test should parse the data row and assert the specific column value to be meaningful.

**⚠️ Should Fix** - `tools/jtk/internal/cmd/dashboards/dashboards.go:120`
> fetchGadgetCounts makes one sequential HTTP call per dashboard with no concurrency, no per-call timeout, and no context propagation (runList discards its context). With --max defaulting to 50, a single `dashboards list` issues up to 50 blocking API calls. A single slow or hung gadget endpoint stalls the entire command indefinitely — there is no deadline to bound the worst case. The comment acknowledges context deferral but not the indefinite-hang risk from an unresponsive upstream.

</details>

<details>
<summary><strong>harness-engineering:harness-knowledge-reviewer (2 findings)</strong></summary>

**💡 Suggestion** - `tools/jtk/internal/present/dashboard.go:218`
> formatPermissions has no case for `projectRole`, `public`, or `authenticated` permission types that Jira returns. These fall through to the default branch and emit the raw API string, which is inconsistent with the explicit human-readable mappings for other types (e.g. `loggedin` → `logged-in`). Add cases or document which types are intentionally out of scope.

**💡 Suggestion** - `tools/jtk/internal/cmd/dashboards/dashboards_test.go:80`
> TestRunList_ColumnOrder and TestRunGadgetsList_ColumnOrder use `strings.Index` on the rendered table header to compare column positions. Any future column whose name contains a substring of another (e.g. `ID` within a hypothetical `GADGET_ID`) would silently break ordering assertions. Asserting against the presenter's TableSection.Headers slice directly — as done in dashboard_test.go — is more robust.

</details>

<details>
<summary><strong>harness-engineering:harness-self-documenting-code-reviewer (1 findings)</strong></summary>

**💡 Suggestion** - `tools/jtk/internal/present/dashboard.go:113`
> The gadget column header is renamed MODULE → TYPE, but the cell value is still `g.ModuleID` (a technical identifier like `com.atlassian.jira.gadgets:filter-results-gadget`). TYPE implies a short category label; what is displayed is a module identifier. MODULE was more accurate, and the rename may confuse users who see a long dotted string under a column labelled TYPE.

</details>

*2 info-level observations excluded. Run with `--verbose` to include.*

*3 PR discussion threads considered.*

---
<details>
<summary>Completed in 3m 35s | $1.16</summary>

| Field | Value |
|---|---|
| Reviewers | hybrid-synthesis, harness-engineering:harness-architecture-reviewer, harness-engineering:harness-enforcement-reviewer, harness-engineering:harness-knowledge-reviewer, harness-engineering:harness-self-documenting-code-reviewer, security:security-code-auditor |
| Engine | claude |
| Reviewed by | [pr-review-daemon](https://github.com/SignalFT/pr-review-daemon) · [monit-pr-reviewer](https://github.com/apps/monit-pr-reviewer) |
| Duration | 3m 35s wall · 7m 59s compute (Reviewers: 2m 12s · Synthesis: 1m 20s) |
| Cost | $1.16 |
| Tokens | 316.1k in / 29.7k out |
| Turns | 16 |

</details>

File: tools/jtk/internal/cmd/dashboards/dashboards_test.go (hunk 1 above)
Comment (rianjs) [reply tools/jtk/internal/cmd/dashboards/dashboards_test.go:222]: Fixed — assertion now splits by agent-table separator and checks GADGETS column (index 1) equals "-" directly.

File: tools/jtk/internal/cmd/dashboards/dashboards_test.go (hunk 5 above)
Comment (rianjs) [reply tools/jtk/internal/cmd/dashboards/dashboards_test.go:80]: Presenter tests already validate exact header order via slice index. Command-level tests add a rendering-contract layer. The substring collision concern is theoretical — column names are distinct by convention.

File: tools/jtk/internal/present/dashboard.go (hunk 6 above)
Comment (rianjs) [reply tools/jtk/internal/present/dashboard.go:113]: Per issue spec (#284): expected column header is TYPE. The ModuleID value is what Jira returns for the gadget type identifier — this matches the product intent from #230.

File: tools/jtk/internal/cmd/dashboards/dashboards.go (hunk 2 above)
Comment (rianjs) [reply tools/jtk/internal/cmd/dashboards/dashboards.go:120]: Acknowledged — intentional deferral documented in the function comment. Dashboard API methods use internal context.Background(); adding per-call timeouts requires changing the public API surface.

File: tools/jtk/internal/cmd/dashboards/dashboards_test.go (hunk 3 above)
Comment (rianjs) [reply tools/jtk/internal/cmd/dashboards/dashboards_test.go:216]: Fixed — changed Popularity to 7 so it is distinct from gadget count (3).

File: tools/jtk/internal/present/dashboard.go (hunk 4 above)
Comment (rianjs) [reply tools/jtk/internal/present/dashboard.go:218]: By design — the default branch emits the raw API type string for unhandled types. This avoids maintaining an exhaustive mapping; common types get readable forms, the rest pass through verbatim.

File: tools/jtk/internal/cmd/dashboards/dashboards_test.go (hunk 1 above)
Comment (monit-reviewer) [reply tools/jtk/internal/cmd/dashboards/dashboards_test.go:222]: **Settled**: monit-reviewer flagged that the GADGETS cell assertion in TestRunList_GadgetFetchFails was vacuous because table separator dashes would always match. rianjs fixed it by splitting on the agent-table separator and checking the GADGETS column (index 1) directly equals "-".

File: tools/jtk/internal/cmd/dashboards/dashboards.go (hunk 2 above)
Comment (monit-reviewer) [reply tools/jtk/internal/cmd/dashboards/dashboards.go:120]: **Settled**: monit-reviewer raised that fetchGadgetCounts makes sequential HTTP calls with no concurrency, per-call timeout, or context propagation, risking indefinite hangs. rianjs acknowledged this as an intentional deferral documented in the function comment, noting that adding per-call timeouts would require changing the public API surface.

File: tools/jtk/internal/cmd/dashboards/dashboards_test.go (hunk 3 above)
Comment (monit-reviewer) [reply tools/jtk/internal/cmd/dashboards/dashboards_test.go:216]: **Settled**: monit-reviewer noted that TestRunList_Extended used the same value (3) for both RANK and gadget count, making the RANK assertion non-distinct. rianjs fixed it by changing Popularity to 7 to uniquely verify the RANK column.

File: tools/jtk/internal/present/dashboard.go (hunk 4 above)
Comment (monit-reviewer) [reply tools/jtk/internal/present/dashboard.go:218]: **Settled**: monit-reviewer flagged that formatPermissions lacks cases for projectRole, public, and authenticated types, causing them to emit raw API strings inconsistently. rianjs explained this is by design — common types get readable forms and the rest pass through verbatim to avoid maintaining an exhaustive mapping.

File: tools/jtk/internal/cmd/dashboards/dashboards_test.go (hunk 5 above)
Comment (monit-reviewer) [reply tools/jtk/internal/cmd/dashboards/dashboards_test.go:80]: **Settled**: monit-reviewer suggested using direct slice assertions instead of strings.Index for column order tests to avoid potential substring collision issues. rianjs explained that presenter tests already validate exact header order via slice index, and the command-level tests serve a distinct rendering-contract purpose; the substring collision concern is theoretical given distinct column names.

File: tools/jtk/internal/present/dashboard.go (hunk 6 above)
Comment (monit-reviewer) [reply tools/jtk/internal/present/dashboard.go:113]: **Settled**: monit-reviewer noted that renaming the gadget column header from MODULE to TYPE is misleading since the cell displays a dotted module identifier like com.atlassian.jira.gadgets:filter-results-gadget. rianjs explained the TYPE header is required by issue spec (#284) and the ModuleID value matches the product intent from issue #230.

File: tools/jtk/internal/cmd/dashboards/dashboards_test.go [hunk 7]
```diff
@@ -39,15 +65,235 @@ func TestRunList(t *testing.T) {
...
+	testutil.Contains(t, out, "group:developers")
+	testutil.Contains(t, out, "7")
+}
+
+func TestRunList_GadgetFetchFails(t *testing.T) {
+	dashboards := []api.Dashboard{
+		{ID: "10001", Name: "Board"},
+	}
+	// Server that returns dashboards but 500s on gadget requests
+	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
```
Comment (monit-reviewer) [inline tools/jtk/internal/cmd/dashboards/dashboards_test.go:203]: 🟡 **Medium** (harness-engineering:harness-enforcement-reviewer): TestRunList_GadgetFetchFails fixes the previous vacuous-dash assertion by splitting the rendered row on " | " and asserting `cols[1] == "-"` via exact equality. However, table renderers typically pad cells to column width, so `cols[1]` may be "-   " (right-padded), causing a spurious failure on correct output. The assertion should trim whitespace before comparing, or use `testutil.Contains` on the full line, to be resilient to renderer padding.

*Reply to this thread when addressed.*

File: tools/jtk/internal/cmd/dashboards/dashboards.go [hunk 8]
```diff
@@ -54,10 +53,12 @@ func newListCmd(opts *root.Options) *cobra.Command {
 	cmd := &cobra.Command{
 		Use:   "list",
```
Comment (monit-reviewer) [inline tools/jtk/internal/cmd/dashboards/dashboards.go:54]: 🔵 **Low** (harness-engineering:harness-enforcement-reviewer): Tests exercise runList by setting opts.IDOnly and opts.Extended directly on the struct, bypassing cobra flag parsing. If --id and --extended are not registered as cobra flags (persistent or otherwise) somewhere in the dashboards command tree, these features are unreachable from the actual CLI and the tests provide false coverage. Verify that both flags are wired into a cobra command registration; if they exist only on the options struct they are dead code to end users.

*Reply to this thread when addressed.*

File: tools/jtk/internal/present/dashboard.go [hunk 9]
```diff
@@ -45,45 +46,72 @@ func (DashboardPresenter) PresentDetail(d *api.Dashboard, gadgets []api.Dashboar
...
 			},
 		},
 	}
 }
 
-// PresentGadgets creates a table view for a list of gadgets.
+// PresentListExtended creates an extended table: ID | GADGETS | OWNER | FAVOURITE | RANK | PERMISSIONS | NAME.
+func (DashboardPresenter) PresentListExtended(dashboards []api.Dashboard, gadgetCounts map[string]int) *present.OutputModel {
+	rows := make([]present.Row, len(dashboards))
+	for i, d := range dashboards {
```
Comment (monit-reviewer) [inline tools/jtk/internal/present/dashboard.go:75]: 🔵 **Low** (harness-engineering:harness-knowledge-reviewer): PresentListExtended renders d.Popularity directly as the RANK column via FormatInt. Because Go zero-initialises int fields, dashboards where Popularity is unset (value 0) display '0' rather than '-' (unknown), making rank-0 and unset dashboards visually indistinguishable. formatGadgetCount uses '-' for the missing-key case; RANK should follow the same convention with a sentinel check (e.g. Popularity <= 0 → '-').

*Reply to this thread when addressed.*

File: tools/jtk/internal/present/dashboard.go [hunk 10]
```diff
@@ -45,45 +46,72 @@ func (DashboardPresenter) PresentDetail(d *api.Dashboard, gadgets []api.Dashboar
...
 		}
 	}
 	return &present.OutputModel{
 		Sections: []present.Section{
 			&present.TableSection{
-				Headers: []string{"ID", "NAME", "OWNER", "FAVOURITE"},
+				Headers: []string{"ID", "GADGETS", "OWNER", "FAVOURITE", "NAME"},
 				Rows:    rows,
 			},
 		},
```
Comment (monit-reviewer) [inline tools/jtk/internal/present/dashboard.go:68]: 🔵 **Low** (harness-engineering:harness-enforcement-reviewer): PresentList and PresentListExtended duplicate the same row-building loop for the first four columns (ID, GADGETS, OWNER, FAVOURITE). If gadget-count formatting or owner rendering changes, both methods must be updated in sync. Extracting the shared cell-building into a private helper reduces maintenance risk and makes the extended variant's additions explicit.

*Reply to this thread when addressed.*

**Review by monit-reviewer — DISMISSED** [review]
## Automated PR Review



**Reviewed commit:** `c125e21` | **Previous:** `68ecd00` (incremental)

### Summary

| Reviewer | Findings |
|----------|----------|
| harness-engineering:harness-enforcement-reviewer | 3 |
| harness-engineering:harness-knowledge-reviewer | 1 |

<details>
<summary><strong>harness-engineering:harness-enforcement-reviewer (3 findings)</strong></summary>

**⚠️ Should Fix** - `tools/jtk/internal/cmd/dashboards/dashboards_test.go:203`
> TestRunList_GadgetFetchFails fixes the previous vacuous-dash assertion by splitting the rendered row on " | " and asserting `cols[1] == "-"` via exact equality. However, table renderers typically pad cells to column width, so `cols[1]` may be "-   " (right-padded), causing a spurious failure on correct output. The assertion should trim whitespace before comparing, or use `testutil.Contains` on the full line, to be resilient to renderer padding.

**💡 Suggestion** - `tools/jtk/internal/cmd/dashboards/dashboards.go:54`
> Tests exercise runList by setting opts.IDOnly and opts.Extended directly on the struct, bypassing cobra flag parsing. If --id and --extended are not registered as cobra flags (persistent or otherwise) somewhere in the dashboards command tree, these features are unreachable from the actual CLI and the tests provide false coverage. Verify that both flags are wired into a cobra command registration; if they exist only on the options struct they are dead code to end users.

**💡 Suggestion** - `tools/jtk/internal/present/dashboard.go:68`
> PresentList and PresentListExtended duplicate the same row-building loop for the first four columns (ID, GADGETS, OWNER, FAVOURITE). If gadget-count formatting or owner rendering changes, both methods must be updated in sync. Extracting the shared cell-building into a private helper reduces maintenance risk and makes the extended variant's additions explicit.

</details>

<details>
<summary><strong>harness-engineering:harness-knowledge-reviewer (1 findings)</strong></summary>

**💡 Suggestion** - `tools/jtk/internal/present/dashboard.go:75`
> PresentListExtended renders d.Popularity directly as the RANK column via FormatInt. Because Go zero-initialises int fields, dashboards where Popularity is unset (value 0) display '0' rather than '-' (unknown), making rank-0 and unset dashboards visually indistinguishable. formatGadgetCount uses '-' for the missing-key case; RANK should follow the same convention with a sentinel check (e.g. Popularity <= 0 → '-').

</details>

*3 info-level observations excluded. Run with `--verbose` to include.*

*9 PR discussion threads considered.*

---
<details>
<summary>Completed in 3m 50s | $1.11</summary>

| Field | Value |
|---|---|
| Mode | Re-review · Cycle 2 · Session resumed |
| Reviewers | hybrid-synthesis, harness-engineering:harness-architecture-reviewer, harness-engineering:harness-enforcement-reviewer, harness-engineering:harness-knowledge-reviewer, harness-engineering:harness-self-documenting-code-reviewer, security:security-code-auditor |
| Engine | claude |
| Reviewed by | [pr-review-daemon](https://github.com/SignalFT/pr-review-daemon) · [monit-pr-reviewer](https://github.com/apps/monit-pr-reviewer) |
| Duration | 3m 50s wall · 8m 08s compute (Reviewers: 1m 50s · Synthesis: 1m 37s) |
| Cost | $1.11 |
| Tokens | 341.6k in / 31.1k out |
| Turns | 15 |

</details>

File: tools/jtk/internal/present/dashboard.go (hunk 9 above)
Comment (rianjs) [reply tools/jtk/internal/present/dashboard.go:75]: Jira API returns 0 for dashboards with no popularity — it's a real value, not unset. Showing '0' is correct.

File: tools/jtk/internal/cmd/dashboards/dashboards.go (hunk 8 above)
Comment (rianjs) [reply tools/jtk/internal/cmd/dashboards/dashboards.go:54]: These are persistent flags registered on the root command (root.go:134-140). Direct struct setting is the standard test pattern used across all jtk command tests.

File: tools/jtk/internal/cmd/dashboards/dashboards_test.go (hunk 7 above)
Comment (rianjs) [reply tools/jtk/internal/cmd/dashboards/dashboards_test.go:203]: False positive — agent-style renderer uses exact ` | ` separator with no padding (see shared/present/render.go:renderAgentTable). The split produces exact cell values.

File: tools/jtk/internal/present/dashboard.go (hunk 10 above)
Comment (rianjs) [reply tools/jtk/internal/present/dashboard.go:68]: Intentionally not abstracting — these are two distinct table layouts and extracting shared columns would be premature. The codebase convention is explicit per-method table construction.

**Comment by rianjs** [comment]
These are low-value, please approve the PR

**Review by monit-reviewer — APPROVED** [review]
## Automated PR Review



**Reviewed commit:** `45d4ebf`

### Human Override

Approved at the request of @rianjs ([comment](https://github.com/open-cli-collective/atlassian-cli/pull/294#issuecomment-4326265052)).

> These are low-value, please approve the PR

No automated reviewers were run.
