### PR TITLE
feat(jtk): fix attachments list --extended column order and get output format

### LINKED ISSUE #290: jtk attachments: fix list --extended column order and get output format
Parent: #230

### `jtk attachments list <key> --extended`
**Current:** `BYTES` and `MIME_TYPE` columns appear after `AUTHOR`/`CREATED`.
**Expected:** `BYTES` and `MIME_TYPE` immediately after `SIZE`, before `AUTHOR`/`CREATED`:
```
ID | FILENAME | SIZE | BYTES | MIME_TYPE | AUTHOR | CREATED
10234 | audit-notes.md | 4.2 KB | 4301 | text/markdown | Aaron Wong | 2026-04-16T09:00:00+0000
10235 | screenshot.png | 182 KB | 186368 | image/png | Aaron Wong | 2026-04-16T09:01:12+0000
```

### `jtk attachments get <id> --output <path>`
**Current:** missing `→` arrow between attachment ID and destination path.
**Expected:**
```
Downloaded 10234 → ./audit-notes.md (4.2 KB)
```

See #230 for full spec.

### PR DESCRIPTION
**Pull request by rianjs**
## Summary
- Reorders `jtk attachments list --extended` columns: BYTES and MIME_TYPE now follow SIZE (before AUTHOR/CREATED)
- Before: `ID | FILENAME | SIZE | AUTHOR | CREATED | BYTES | MIME_TYPE`
- After: `ID | FILENAME | SIZE | BYTES | MIME_TYPE | AUTHOR | CREATED`
- Updates `attachments get` output to include attachment ID and arrow: `Downloaded 10234 → ./file.md (4.2 KB)`

Closes #290

## Test plan
- [x] Spec-lock test verifies header order for both default and extended modes
- [x] Extended test asserts exact header order and all cell positions
- [x] PresentDownloaded test verifies new 3-arg signature and `→` format
- [x] Command-level TestRunGet_Success asserts exact output format
- [x] `make build && make test && make lint` all pass

### CODE REVIEW

**Comment by rianjs** [comment]
**Blocker**
- None.

**Major**
- None.

**Minor**
- [tools/jtk/internal/cmd/attachments/attachments_test.go:441](/Users/rianjs/dev/atlassian-cli/tools/jtk/internal/cmd/attachments/attachments_test.go:441) The command-level test still does substring checks, despite the plan/PR claiming exact output coverage. It would not catch dropping the size suffix or changing the resolved path format. Add one assertion for the full rendered message, e.g. `Downloaded 10001 → <outputPath> (36 B)`.

**Nit**
- None.

**Comment by rianjs** [comment]
## Test Coverage Review

### Missing: nil/empty MimeType in extended list

`TestAttachmentPresenter_PresentList_Extended` uses `MimeType: "text/markdown"` exclusively. `OrDash` is called for MIME_TYPE in the extended path — there's no test verifying that a blank or zero-value `MimeType` renders as `-` instead of an empty cell. This is the most common real-world case (many Jira attachments omit MIME type).

### Missing: default-mode cell order regression test

`TestAttachmentPresenter_PresentList_Extended` now exhaustively asserts all 7 cells in order. The default (non-extended) path has no equivalent per-cell assertion — only the `TestAttachmentListSpec_MatchesPresentListHeaders` spec-alignment check. If someone swaps AUTHOR/CREATED in the default `else` branch, no test catches it. A parallel default-mode cell-order test would close the gap.

### Asymmetry: extended uses `OrDash(a.Created)`, default uses `FormatTime(a.Created)`

Both paths are exercised indirectly, but neither test verifies what a zero-value `Created` produces in each mode. The extended path calls `OrDash` (returns `-`), the default path calls `FormatTime` (behavior depends on that helper). Worth a note or a test — probably intentional, but silently divergent.

### Download path coverage: directory output path not tested

`TestRunGet_Success` passes a full file path (`filepath.Join(tmpDir, "downloaded.txt")`). `runGet` has logic to handle a directory output path (appending the filename). That branch is untested. Not introduced by this PR, but the updated message assertion now makes the exact path load-bearing — a directory-path test would catch any regression there too.

### What's covered well

- Header order assertion is now exhaustive (all 7 headers checked by index)
- Cell order assertion for extended mode checks all 7 cells in the new order
- `PresentDownloaded` message format with ID and arrow is explicitly asserted
- `TestRunGet_Success` uses `fmt.Sprintf` to build the expected string, so it tracks the real output path correctly

File: tools/jtk/internal/present/attachment_test.go [hunk 1]
```diff
@@ -52,28 +105,35 @@ func TestAttachmentPresenter_PresentList_Extended(t *testing.T) {
 		Author:   api.User{DisplayName: "Alice"},
```
Comment (monit-reviewer) [inline tools/jtk/internal/present/attachment_test.go:105]: 🔵 **Low** (harness-engineering:harness-enforcement-reviewer): TestAttachmentPresenter_PresentList_Default_CellOrder only asserts cells[0] (ID), cells[1] (FILENAME), and cells[3] (AUTHOR) but skips cells[2] (SIZE) and cells[4] (CREATED). If someone swaps AUTHOR/CREATED or reorders SIZE in the default branch, no test catches it. The extended test is exhaustive; the default test should be too.

*Reply to this thread when addressed.*

File: tools/jtk/internal/cmd/attachments/attachments_test.go [hunk 2]
```diff
@@ -438,10 +438,10 @@ func TestRunGet_Success(t *testing.T) {
 	testutil.RequireNoError(t, err)
 	testutil.Equal(t, string(content), fileContent)
 
-	// Verify success message
+	// Verify exact success message format
```
Comment (monit-reviewer) [inline tools/jtk/internal/cmd/attachments/attachments_test.go:441]: 🔵 **Low** (harness-engineering:harness-architecture-reviewer): The command-level test uses substring/contains checks rather than asserting the full rendered message. It would not catch dropping the size suffix or changing the resolved path format. Assert the exact full output, e.g. `Downloaded 10001 → <outputPath> (36 B)`, to match what the PR description claims.

*Reply to this thread when addressed.*

File: tools/jtk/internal/present/attachment.go [hunk 3]
```diff
@@ -14,23 +14,24 @@ import (
 type AttachmentPresenter struct{}
 
 // AttachmentListSpec declares the columns emitted by PresentList. Default:
-// ID|FILENAME|SIZE|AUTHOR|CREATED. Extended adds BYTES and MIME_TYPE.
+// ID|FILENAME|SIZE|AUTHOR|CREATED. Extended:
```
Comment (monit-reviewer) [inline tools/jtk/internal/present/attachment.go:17]: 🔵 **Low** (harness-engineering:harness-enforcement-reviewer): [Pre-existing] AttachmentListSpec (the projection.Registry) and the hardcoded header/cell slices inside PresentList are parallel data structures. The spec-lock test catches count mismatches but not position mismatches for non-extended columns. This structural issue predates this PR but is made more visible by the reorder.

*Reply to this thread when addressed.*

**Review by monit-reviewer — APPROVED** [review]
## Automated PR Review



**Reviewed commit:** `de85901`

> **Approved** with 3 non-blocking suggestions below. Address at your discretion.

### Summary

| Reviewer | Findings |
|----------|----------|
| harness-engineering:harness-architecture-reviewer | 1 |
| harness-engineering:harness-enforcement-reviewer | 2 |

<details>
<summary><strong>harness-engineering:harness-architecture-reviewer (1 findings)</strong></summary>

**💡 Suggestion** - `tools/jtk/internal/cmd/attachments/attachments_test.go:441`
> The command-level test uses substring/contains checks rather than asserting the full rendered message. It would not catch dropping the size suffix or changing the resolved path format. Assert the exact full output, e.g. `Downloaded 10001 → <outputPath> (36 B)`, to match what the PR description claims.

</details>

<details>
<summary><strong>harness-engineering:harness-enforcement-reviewer (2 findings)</strong></summary>

**💡 Suggestion** - `tools/jtk/internal/present/attachment_test.go:105`
> TestAttachmentPresenter_PresentList_Default_CellOrder only asserts cells[0] (ID), cells[1] (FILENAME), and cells[3] (AUTHOR) but skips cells[2] (SIZE) and cells[4] (CREATED). If someone swaps AUTHOR/CREATED or reorders SIZE in the default branch, no test catches it. The extended test is exhaustive; the default test should be too.

**💡 Suggestion** - `tools/jtk/internal/present/attachment.go:17`
> [Pre-existing] AttachmentListSpec (the projection.Registry) and the hardcoded header/cell slices inside PresentList are parallel data structures. The spec-lock test catches count mismatches but not position mismatches for non-extended columns. This structural issue predates this PR but is made more visible by the reorder.

</details>

*1 info-level observations excluded. Run with `--verbose` to include.*

*2 PR discussion threads considered.*

---
<details>
<summary>Completed in 1m 15s | $0.54</summary>

| Field | Value |
|---|---|
| Reviewers | hybrid-synthesis, harness-engineering:harness-architecture-reviewer, harness-engineering:harness-enforcement-reviewer, harness-engineering:harness-knowledge-reviewer, harness-engineering:harness-self-documenting-code-reviewer, security:security-code-auditor |
| Engine | claude |
| Reviewed by | [pr-review-daemon](https://github.com/SignalFT/pr-review-daemon) · [monit-pr-reviewer](https://github.com/apps/monit-pr-reviewer) |
| Duration | 1m 15s wall · 3m 55s compute (Reviewers: 53s · Synthesis: 19s) |
| Cost | $0.54 |
| Tokens | 176.0k in / 14.0k out |
| Turns | 14 |

</details>

File: tools/jtk/internal/present/attachment_test.go (hunk 1 above)
Comment (rianjs) [reply tools/jtk/internal/present/attachment_test.go:105]: Low-value — the spec-lock test catches header order, and the extended test is exhaustive. Adding 2 more assertions to default would be marginal. Accepted as-is.

File: tools/jtk/internal/cmd/attachments/attachments_test.go (hunk 2 above)
Comment (rianjs) [reply tools/jtk/internal/cmd/attachments/attachments_test.go:441]: Already fixed in the latest commit — the test now asserts the exact full message: 'Downloaded 10001 → <path> (36 B)'.

File: tools/jtk/internal/present/attachment.go (hunk 3 above)
Comment (rianjs) [reply tools/jtk/internal/present/attachment.go:17]: Pre-existing structural pattern — the spec-lock test is the guard. Not in scope for this PR.
