### PR TITLE
feat(jtk): fix automation list/get output format and wire --id/--extended flags

### LINKED ISSUE #283: jtk automation: fix list/get output format and wire --id/--extended flags
Parent: #230

### `jtk automation list` (default)
**Current:** column order `UUID | NAME | STATE`; header says `UUID` not `ID`.
**Expected:**
```
ID | STATE | NAME
018c2840-57c1-7869-9393-11205cc87ce4 | ENABLED | ON/MON: Create Onboarding Tasks
019d95ba-031c-7000-88df-134a1c924860 | DISABLED | [Archive] Old closer
```

### `jtk automation list --id`
**Current:** flag not wired — output identical to default.
**Expected:** one ID per line.

### `jtk automation list --extended`
**Current:** flag not wired — output identical to default.
**Expected:**
```
ID | STATE | LABELS | TAGS | AUTHOR | NAME
018c2840-57c1-7869-9393-11205cc87ce4 | ENABLED | onboarding | auto-create | Rian Stockbower | ON/MON: Create Onboarding Tasks
```

### `jtk automation get <id>` (default)
**Current:** no header line; uses labeled-field format; field order differs.
**Expected:**
```
018c2840-57c1-7869-9393-11205cc87ce4  ON/MON: Create Onboarding Tasks
State: ENABLED
Components: 27 total — 4 conditions, 23 actions
Description: Creates Tasks when a new Onboarding Epic is created
```

### `jtk automation get <id> --id`
**Current:** flag not wired — output identical to default.
**Expected:** UUID only.

### `jtk automation get <id> --extended`
**Current:** flag not wired — output identical to default.
**Expected:** adds Labels, Tags, Author, Scope, Created, Updated on top of default:
```
Labels: onboarding
Tags: auto-create
Author: Rian Stockbower
Scope: project (MON, ON)
Created: 2023-12-04   Updated: 2026-03-15
```

See #230 for full spec.

### PR DESCRIPTION
**Pull request by rianjs**
Closes #283

## Summary
- Reorder `automation list` columns to ID|STATE|NAME (was UUID|NAME|STATE)
- Wire `--id` flag for both list and get (one ID per line)
- Wire `--extended` for list (adds LABELS, TAGS, AUTHOR columns with live user resolution)
- Add get-specific detail format: header line (ID + Name) + KV rows, matching issue/project pattern
- Extended get adds Labels, Tags, Author, Scope, Created, Updated
- Fix `SummarizeComponents` pluralization: "conditions" not "condition(s)"
- Add `Created`/`Updated` typed fields to automation API types
- Preserve `--show-components` in both default and extended paths
- Use `Emit` helpers consistently instead of manual `Render`+`Fprint`

## Test plan
- [ ] `jtk automation list` shows ID|STATE|NAME columns
- [ ] `jtk automation list --id` shows one UUID per line
- [ ] `jtk automation list --extended` shows LABELS, TAGS, AUTHOR columns
- [ ] `jtk automation get <id>` shows header line format
- [ ] `jtk automation get <id> --id` shows UUID only
- [ ] `jtk automation get <id> --extended` shows Labels, Tags, Author, Scope, Created, Updated
- [ ] `jtk automation get <id> --show-components` still works
- [ ] `make test` passes
- [ ] `make lint` passes (jtk clean)

### CODE REVIEW

**Comment by rianjs** [comment]
**Major**
- `tools/jtk/internal/cmd/automation/list.go:46` handles the empty-result branch before `opts.EmitIDOnly()`. `jtk automation list --id` with no matching rules will emit `No automation rules found`, violating the machine-friendly `--id` contract of one ID per line and no prose. Move the `--id` branch before the empty presenter and add an empty `--id` test.

**Minor**
- `tools/jtk/internal/present/automation.go:372` now renders `1 triggers`, `1 conditions`, `1 actions`, and the tests codify that at `tools/jtk/internal/cmd/automation/get_test.go:35`. The product intent was to remove `(s)` noise, not introduce ungrammatical singular counts. Use normal pluralization: `1 trigger`, `2 triggers`.

Verification note: I attempted focused `go test`, but this sandbox blocks `httptest` listeners (`bind: operation not permitted`), so I did not use test results as a PR signal.

**Comment by rianjs** [comment]
No findings. The revised diff now preserves the intended `--id` empty-output contract, keeps `PresentDetail` isolated for mutation callers, preserves `--show-components`, and renders component counts with proper singular/plural wording.

**Comment by rianjs** [comment]
## TDD Assessment — PR #293

### Overall verdict: solid coverage, three gaps worth noting

---

### What's well covered

**`get_test.go` — integration-level (5 tests)**
- Default output (`TestRunGet_Default`): asserts header line, State, Components, Description
- `--id` flag (`TestRunGet_IDOnly`): asserts UUID present, Name/State suppressed
- `--extended` flag (`TestRunGet_Extended`): asserts Labels, Tags, Author (resolved), Scope, Created, Updated
- `--show-components` (`TestRunGet_ShowComponents`): asserts component table headers/rows
- `TestRunGet_Extended` wires a real mock `/rest/api/3/user` response — author resolution is exercised end-to-end

**`list_test.go` — integration-level (6 tests)**
- Default column order (`TestRunList_Default_ColumnOrder`): asserts ID/STATE/NAME and absence of "UUID"
- `--id` flag: asserts both IDs present, Name/STATE suppressed
- `--extended` flag: asserts LABELS/TAGS/AUTHOR columns and resolved display name
- Empty results default (`TestRunList_Empty`): asserts "No automation rules found"
- `--id` with empty results (`TestRunList_IDOnly_Empty`): asserts no output emitted

**`automation_test.go` — presenter-unit-level (new tests)**
- `PresentList` column ordering pin test
- `PresentListExtended`: header order, resolved author, empty-labels → dash fallback
- `PresentGetDetail`: section count, header message, state line
- `PresentGetDetail` + `showComponents=true`: component table appended at [3]
- `PresentGetDetailExtended`: section count (9), scope string, timestamp formatting
- `TestAutomationScope`: projects, ARIs, global — three branches all hit
- `SummarizeComponents` pluralization: single/plural corrected and verified across 4 cases in both files

---

### Gaps

**1. `resolveAuthorNames` error path — not directly tested**
When `GetUser` fails the implementation silently `continue`s, leaving the author entry absent from the map. The list extended test only exercises the success path. There is no test asserting that a rule with a lookup failure falls back to rendering the raw account ID in the table row (the fallback is in `resolveAuthor`, which is exercised by the presenter unit test for an *absent key*, but the list integration path for an API-error author is not covered).

**2. `--extended` get with `AuthorAccountID == ""` — not tested**
`runGet` only calls `GetUser` when `AuthorAccountID != ""`. There is no test for a rule that has no author at all going through the extended path. The `OrDash(authorName)` fallback would render "-", but this is unverified at the integration level.

**3. `--id` precedes empty-results check in `runList`**
The ordering in `runList` is: EmitIDOnly → empty check → JSON → extended → default. `TestRunList_IDOnly_Empty` covers the case and passes, but the empty extended path (`--extended` with zero rules) is not tested — the code would call `resolveAuthorNames` with an empty slice and then `PresentListExtended` with an empty `rules` slice, producing an empty table. Low risk but untested.

---

### Minor observations

- `TestRunGet_Default` and `TestRunGet_ShowComponents` are not marked `t.Parallel()` while the presenter unit tests are. Inconsistent but not a correctness issue.
- `automationSummaryAuthorIDs` (dedup logic) has no dedicated unit test — covered implicitly only when multiple rules share an account ID. A direct unit test would be cheap given the isolation.
- The `PresentGetDetail` test verifies section count (4) and spot-checks [0] and [1] but does not assert the Components or Description lines. Not a blocker, just a shallow assertion.

---

### Summary

The three main code paths (`--id`, `--extended`, default) are all exercised with real HTTP mock servers for both commands. The pluralization fix is pinned with before/after expectations. The scope branches (projects/ARIs/global) are explicitly enumerated. The primary gap is the author-resolution failure path at the integration level — a `GetUser` error should produce raw account ID output in `runList --extended`, and that is not verified.

File: tools/jtk/internal/cmd/automation/list.go [hunk 1]
```diff
@@ -43,22 +43,53 @@ func runList(ctx context.Context, opts *root.Options, state string) error {
...
+		return jtkpresent.EmitIDs(opts, ids)
+	}
+
 	if len(rules) == 0 {
-		model := jtkpresent.AutomationPresenter{}.PresentEmpty()
-		out := present.Render(model, opts.RenderStyle())
-		fmt.Fprint(opts.Stdout, out.Stdout)
-		return nil
+		return jtkpresent.Emit(opts, jtkpresent.AutomationPresenter{}.PresentEmpty())
 	}
```
Comment (monit-reviewer) [inline tools/jtk/internal/cmd/automation/list.go:59]: 🔵 **Low** (harness-engineering:harness-enforcement-reviewer): Format check uses the raw string literal "json" instead of the view.FormatJSON constant that get.go uses. If the constant value ever changes, list.go silently diverges. Use `view.FormatJSON` for consistency and safety.

*Reply to this thread when addressed.*

File: tools/jtk/internal/cmd/automation/get_test.go [hunk 2]
```diff
@@ -65,3 +71,178 @@ func TestSummarizeComponents(t *testing.T) {
 		})
```
Comment (monit-reviewer) [inline tools/jtk/internal/cmd/automation/get_test.go:72]: 🟡 **Medium** (harness-engineering:harness-self-documenting-code-reviewer): No test covers the case where AuthorAccountID is set but GetUser fails (API error). list_test.go has TestRunList_Extended_AuthorFallback for this exact scenario, but the equivalent is absent from get_test.go. The get.go else-branch (authorName = rule.AuthorAccountID) is untested for the error path.

*Reply to this thread when addressed.*

File: tools/jtk/internal/present/automation.go [hunk 3]
```diff
@@ -218,25 +218,143 @@ func (AutomationPresenter) PresentEmpty() *present.OutputModel {
...
+	if showComponents && len(rule.Components) > 0 {
+		sections = append(sections, componentTable(rule.Components))
+	}
+
+	return &present.OutputModel{Sections: sections}
+}
+
+func componentTable(components []api.RuleComponent) *present.TableSection {
+	rows := make([]present.Row, len(components))
+	for i, c := range components {
```
Comment (monit-reviewer) [inline tools/jtk/internal/present/automation.go:310]: 🔵 **Low** (harness-engineering:harness-architecture-reviewer): PresentGetDetailExtended combines Created and Updated on a single line ('Created: X   Updated: Y') using triple-space as separator. Every other field in the KV layout gets its own line. Splitting into two separate sections would be consistent with the rest of the layout and easier to grep/test.

*Reply to this thread when addressed.*

File: tools/jtk/internal/present/automation.go [hunk 4]
```diff
@@ -218,25 +218,143 @@ func (AutomationPresenter) PresentEmpty() *present.OutputModel {
...
+		keys := make([]string, 0, len(rule.Projects))
+		for _, p := range rule.Projects {
+			if p.ProjectKey != "" {
+				keys = append(keys, p.ProjectKey)
+			} else if p.ProjectName != "" {
+				keys = append(keys, p.ProjectName)
+			}
+		}
+		if len(keys) > 0 {
+			return fmt.Sprintf("project (%s)", strings.Join(keys, ", "))
```
Comment (monit-reviewer) [inline tools/jtk/internal/present/automation.go]: 🔵 **Low** (harness-engineering:harness-architecture-reviewer): automationScope: a rule whose Projects slice is non-empty but every project has both empty ProjectKey and empty ProjectName silently produces zero keys, falls through to the RuleScopeARIs check, and may incorrectly report 'scoped' or 'global'. No test covers this path. Add a guard or document the assumption that at least one identifier is always present.

*Reply to this thread when addressed.*

File: tools/jtk/internal/cmd/automation/get_test.go [hunk 5]
```diff
@@ -65,3 +71,178 @@ func TestSummarizeComponents(t *testing.T) {
...
 	}
 }
+
```
Comment (monit-reviewer) [inline tools/jtk/internal/cmd/automation/get_test.go:75]: 🔵 **Low** (harness-engineering:harness-architecture-reviewer): newGetTestServer uses a catch-all handler: any request path not explicitly matched returns the encoded AutomationRule. A mis-routed API call silently returns plausible data instead of failing the test. Consider returning http.StatusNotFound for unrecognised paths so test infrastructure bugs surface immediately.

*Reply to this thread when addressed.*

**Review by monit-reviewer — DISMISSED** [review]
## Automated PR Review



**Reviewed commit:** `4800c2d`

### Summary

| Reviewer | Findings |
|----------|----------|
| harness-engineering:harness-architecture-reviewer | 3 |
| harness-engineering:harness-enforcement-reviewer | 1 |
| harness-engineering:harness-self-documenting-code-reviewer | 1 |

<details>
<summary><strong>harness-engineering:harness-architecture-reviewer (3 findings)</strong></summary>

**💡 Suggestion** - `tools/jtk/internal/present/automation.go:310`
> PresentGetDetailExtended combines Created and Updated on a single line ('Created: X   Updated: Y') using triple-space as separator. Every other field in the KV layout gets its own line. Splitting into two separate sections would be consistent with the rest of the layout and easier to grep/test.

**💡 Suggestion** - `tools/jtk/internal/present/automation.go:332`
> automationScope: a rule whose Projects slice is non-empty but every project has both empty ProjectKey and empty ProjectName silently produces zero keys, falls through to the RuleScopeARIs check, and may incorrectly report 'scoped' or 'global'. No test covers this path. Add a guard or document the assumption that at least one identifier is always present.

**💡 Suggestion** - `tools/jtk/internal/cmd/automation/get_test.go:74`
> newGetTestServer uses a catch-all handler: any request path not explicitly matched returns the encoded AutomationRule. A mis-routed API call silently returns plausible data instead of failing the test. Consider returning http.StatusNotFound for unrecognised paths so test infrastructure bugs surface immediately.

</details>

<details>
<summary><strong>harness-engineering:harness-enforcement-reviewer (1 findings)</strong></summary>

**💡 Suggestion** - `tools/jtk/internal/cmd/automation/list.go:57`
> Format check uses the raw string literal "json" instead of the view.FormatJSON constant that get.go uses. If the constant value ever changes, list.go silently diverges. Use `view.FormatJSON` for consistency and safety.

</details>

<details>
<summary><strong>harness-engineering:harness-self-documenting-code-reviewer (1 findings)</strong></summary>

**⚠️ Should Fix** - `tools/jtk/internal/cmd/automation/get_test.go:71`
> No test covers the case where AuthorAccountID is set but GetUser fails (API error). list_test.go has TestRunList_Extended_AuthorFallback for this exact scenario, but the equivalent is absent from get_test.go. The get.go else-branch (authorName = rule.AuthorAccountID) is untested for the error path.

</details>

*1 info-level observations excluded. Run with `--verbose` to include.*

*3 PR discussion threads considered.*

---
<details>
<summary>Completed in 2m 33s | $1.07</summary>

| Field | Value |
|---|---|
| Reviewers | hybrid-synthesis, harness-engineering:harness-architecture-reviewer, harness-engineering:harness-enforcement-reviewer, harness-engineering:harness-knowledge-reviewer, harness-engineering:harness-self-documenting-code-reviewer, security:security-code-auditor |
| Engine | claude |
| Reviewed by | [pr-review-daemon](https://github.com/SignalFT/pr-review-daemon) · [monit-pr-reviewer](https://github.com/apps/monit-pr-reviewer) |
| Duration | 2m 33s wall · 7m 48s compute (Reviewers: 1m 49s · Synthesis: 41s) |
| Cost | $1.07 |
| Tokens | 376.6k in / 28.5k out |
| Turns | 18 |

</details>

File: tools/jtk/internal/cmd/automation/list.go (hunk 1 above)
Comment (rianjs) [reply tools/jtk/internal/cmd/automation/list.go:59]: Fixed — now using view.FormatJSON constant.

File: tools/jtk/internal/cmd/automation/get_test.go (hunk 2 above)
Comment (rianjs) [reply tools/jtk/internal/cmd/automation/get_test.go:72]: Fixed — added TestRunGet_Extended_AuthorLookupFails that verifies the fallback to raw account ID when GetUser returns 404.

File: tools/jtk/internal/present/automation.go (hunk 3 above)
Comment (rianjs) [reply tools/jtk/internal/present/automation.go:310]: Intentional — the issue spec shows Created and Updated on one line, matching the issue detail pattern where Status/Type/Priority share a line.

File: tools/jtk/internal/present/automation.go (hunk 4 above)
Comment (rianjs) [reply tools/jtk/internal/present/automation.go]: Fixed — automationScope now builds keys unconditionally, so empty-identifier projects fall through correctly to ARIs/global.

File: tools/jtk/internal/cmd/automation/get_test.go (hunk 5 above)
Comment (rianjs) [reply tools/jtk/internal/cmd/automation/get_test.go:75]: Fixed — newGetTestServer now uses strict path matching with 404 for unrecognized paths.

File: tools/jtk/internal/cmd/automation/list.go (hunk 1 above)
Comment (monit-reviewer) [reply tools/jtk/internal/cmd/automation/list.go:59]: **Settled**: monit-reviewer flagged use of raw string 'json' instead of the view.FormatJSON constant. rianjs fixed it to use the constant.

File: tools/jtk/internal/cmd/automation/get_test.go (hunk 2 above)
Comment (monit-reviewer) [reply tools/jtk/internal/cmd/automation/get_test.go:72]: **Settled**: monit-reviewer noted the missing test for the AuthorAccountID fallback when GetUser fails. rianjs added TestRunGet_Extended_AuthorLookupFails to cover the error path.

File: tools/jtk/internal/present/automation.go (hunk 3 above)
Comment (monit-reviewer) [reply tools/jtk/internal/present/automation.go:310]: **Settled**: monit-reviewer suggested splitting Created and Updated onto separate lines for layout consistency. rianjs explained this is intentional per the issue spec, which shows them on one line.

File: tools/jtk/internal/present/automation.go (hunk 4 above)
Comment (monit-reviewer) [reply tools/jtk/internal/present/automation.go]: **Settled**: monit-reviewer flagged that automationScope could silently produce zero keys for projects with empty identifiers. rianjs fixed it so empty-identifier projects fall through correctly to ARIs/global.

File: tools/jtk/internal/cmd/automation/get_test.go (hunk 5 above)
Comment (monit-reviewer) [reply tools/jtk/internal/cmd/automation/get_test.go:75]: **Settled**: monit-reviewer noted the catch-all handler in newGetTestServer could mask mis-routed API calls. rianjs fixed it to use strict path matching with 404 for unrecognized paths.

File: tools/jtk/internal/cmd/automation/get_test.go [hunk 6]
```diff
@@ -65,3 +72,220 @@ func TestSummarizeComponents(t *testing.T) {
...
+	opts.SetAPIClient(client)
+
+	err = runGet(context.Background(), opts, "uuid-123", true)
+	testutil.RequireNoError(t, err)
+
+	out := stdout.String()
+	testutil.Contains(t, out, "COMPONENT")
+	testutil.Contains(t, out, "TRIGGER")
+	testutil.Contains(t, out, "ACTION")
+}
```
Comment (monit-reviewer) [inline tools/jtk/internal/cmd/automation/get_test.go:291]: 🔵 **Low** (harness-engineering:harness-self-documenting-code-reviewer): No integration-level test covers --show-components combined with --extended. The PR description explicitly claims this combination is preserved in both paths, but only the plain --show-components path is tested end-to-end (TestRunGet_ShowComponents). A regression in PresentGetDetailExtended's showComponents branch would go undetected at the integration level. Unit-level presenter coverage exists but does not exercise the full runGet path with live user resolution.

*Reply to this thread when addressed.*

File: tools/jtk/internal/present/automation.go [hunk 7]
```diff
@@ -218,25 +218,141 @@ func (AutomationPresenter) PresentEmpty() *present.OutputModel {
...
+}
+
+// PresentGetDetail creates the get-specific detail view with header line + KV rows.
+func (AutomationPresenter) PresentGetDetail(rule *api.AutomationRule, showComponents bool) *present.OutputModel {
+	sections := []present.Section{
+		msg(fmt.Sprintf("%s  %s", rule.Identifier(), rule.Name)),
+		msg(fmt.Sprintf("State: %s", rule.State)),
+		msg(fmt.Sprintf("Components: %s", SummarizeComponents(rule.Components))),
+	}
+
```
Comment (monit-reviewer) [inline tools/jtk/internal/present/automation.go:270]: 🔵 **Low** (harness-engineering:harness-self-documenting-code-reviewer): PresentGetDetail and PresentGetDetailExtended share identical leading logic (header, state, components summary, optional description) that is copy-pasted rather than extracted into a shared helper. A future change to the default layout must be applied in two places and kept in sync manually.

*Reply to this thread when addressed.*

File: tools/jtk/internal/present/automation.go [hunk 8]
```diff
@@ -218,25 +218,141 @@ func (AutomationPresenter) PresentEmpty() *present.OutputModel {
...
+	if accountID == "" {
+		return "-"
+	}
+	if name, ok := authorNames[accountID]; ok {
+		return name
+	}
+	return accountID
+}
+
 // SummarizeComponents creates a compact summary of rule components.
```
Comment (monit-reviewer) [inline tools/jtk/internal/present/automation.go:356]: 🔵 **Low** (harness-engineering:harness-knowledge-reviewer): automationScope() returns the opaque string "scoped" when RuleScopeARIs is non-empty but Projects is empty. Users see no actionable information about what the scope actually is. Consider showing the ARI count (e.g., "scoped (3 ARIs)") or the first ARI value, consistent with how the Projects path shows its keys.

*Reply to this thread when addressed.*

**Review by monit-reviewer — APPROVED** [review]
## Automated PR Review



**Reviewed commit:** `1a36388` | **Previous:** `4800c2d` (incremental)

> **Approved** with 3 non-blocking suggestions below. Address at your discretion.

### Summary

| Reviewer | Findings |
|----------|----------|
| harness-engineering:harness-knowledge-reviewer | 1 |
| harness-engineering:harness-self-documenting-code-reviewer | 2 |

<details>
<summary><strong>harness-engineering:harness-knowledge-reviewer (1 findings)</strong></summary>

**💡 Suggestion** - `tools/jtk/internal/present/automation.go:356`
> automationScope() returns the opaque string "scoped" when RuleScopeARIs is non-empty but Projects is empty. Users see no actionable information about what the scope actually is. Consider showing the ARI count (e.g., "scoped (3 ARIs)") or the first ARI value, consistent with how the Projects path shows its keys.

</details>

<details>
<summary><strong>harness-engineering:harness-self-documenting-code-reviewer (2 findings)</strong></summary>

**💡 Suggestion** - `tools/jtk/internal/cmd/automation/get_test.go:291`
> No integration-level test covers --show-components combined with --extended. The PR description explicitly claims this combination is preserved in both paths, but only the plain --show-components path is tested end-to-end (TestRunGet_ShowComponents). A regression in PresentGetDetailExtended's showComponents branch would go undetected at the integration level. Unit-level presenter coverage exists but does not exercise the full runGet path with live user resolution.

**💡 Suggestion** - `tools/jtk/internal/present/automation.go:270`
> PresentGetDetail and PresentGetDetailExtended share identical leading logic (header, state, components summary, optional description) that is copy-pasted rather than extracted into a shared helper. A future change to the default layout must be applied in two places and kept in sync manually.

</details>

*1 info-level observations excluded. Run with `--verbose` to include.*

*8 PR discussion threads considered.*

---
<details>
<summary>Completed in 4m 18s | $1.20</summary>

| Field | Value |
|---|---|
| Mode | Re-review · Cycle 2 · Session resumed |
| Reviewers | hybrid-synthesis, harness-engineering:harness-architecture-reviewer, harness-engineering:harness-enforcement-reviewer, harness-engineering:harness-knowledge-reviewer, harness-engineering:harness-self-documenting-code-reviewer, security:security-code-auditor |
| Engine | claude |
| Reviewed by | [pr-review-daemon](https://github.com/SignalFT/pr-review-daemon) · [monit-pr-reviewer](https://github.com/apps/monit-pr-reviewer) |
| Duration | 4m 18s wall · 9m 46s compute (Reviewers: 2m 31s · Synthesis: 1m 30s) |
| Cost | $1.20 |
| Tokens | 445.9k in / 33.6k out |
| Turns | 18 |

</details>
